(function(g){var window=this;'use strict';var V3=function(a){a.ra("cardstatechange",a.Mk()&&a.Zo()?1:0)},W3=function(a,b){var c=g.ab(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Vlb=function(a){var b=g.ts(a);
a=g.ws(a);return new g.hs(b.x,b.y,a.width,a.height)},Wlb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.IC(a,b,function(){g.JC(e);c.apply(a,arguments)},d)},Z3=function(a){a=g.fb(a);
delete X3[a];g.md(X3)&&Y3&&Y3.stop()},Ylb=function(){Y3||(Y3=new g.Qu(function(){Xlb()},20));
var a=Y3;a.isActive()||a.start()},Xlb=function(){var a=g.kb();
g.bd(X3,function(b){Zlb(b,a)});
g.md(X3)||Ylb()},$3=function(a,b,c,d){g.cv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Zlb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;$lb(a,a.progress);1==a.progress?(a.j=0,Z3(a),a.onFinish(),a.ir()):a.isPlaying()&&a.yL()},$lb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},amb=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},a4=function(a,b,c,d,e){$3.call(this,b,c,d,e);
this.element=a},bmb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
a4.call(this,a,b,c,d,e)},cmb=function(a){return Math.pow(a,3)},dmb=function(a){return 3*a*a-2*a*a*a},emb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},b4=function(a){return a.baseUrl||null},c4=function(a,b){return g.ot(g.Er(a,b),function(c){return!!c})},fmb=function(a,b,c){function d(ta){var ka=ta.hovercardButton;
if(!ka)return null;ka=ka.subscribeButtonRenderer;if(!ka)return null;var va=f(ka.unsubscribedButtonText),ea=f(ka.subscribedButtonText);if(ka.subscribed){var Y=f(ka.subscriberCountWithUnsubscribeText);var Ma=f(ka.subscriberCountText)}else Y=f(ka.subscriberCountText),Ma=f(ka.subscriberCountWithSubscribeText);var y=null;if(ta.signinEndpoint){y=W3(ta,"signinEndpoint","webNavigationEndpointData","url");if(!y){var aa,Ua;y=null==(Ua=g.U(null==(aa=ka.signInEndpoint)?void 0:aa.commandMetadata,g.Q2))?void 0:
Ua.url}if(!y)return null}return va&&(ea||y)?{subscribed:ka.subscribed,subscribeText:va,subscribeCount:Y,unsubscribeText:ea,unsubscribeCount:Ma,enabled:ka.enabled,signinUrl:y,classic:ta.useClassicSubscribeButton}:null}
function e(ta){if(ta){var ka=[],va=ta.videoId;va&&ka.push("v="+va);(va=ta.playlistId)&&ka.push("list="+va);(ta=ta.startTimeSeconds)&&ka.push("t="+ta);return"/watch?"+ka.join("&")}}
function f(ta){if(!ta)return null;var ka=ta.simpleText;return ka?ka:ta.runs?g.Er(ta.runs,function(va){return va.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,A=null,E=null,F=null,G=null,M=null,P=null;if("VIDEO"===h)g.U(l,g.yG)?m=g.U(l,g.yG).url:(P=g.U(l,g.qT),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.yG)?m=g.U(l,g.yG).url:(P=g.U(l,g.qT),m=e(P)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=W3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?A=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((F=W3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=W3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=W3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ba="";if(b.metadata){var na=f(b.metadata);na&&(ba=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ba,callToAction:f(b.callToAction),jW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,bE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:E,isSubscribe:x,targetUrl:m||null,t8:n,sessionData:R?{itct:R}:null,Sca:q,DC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:c4(b.impressionUrls||[],b4),g8:c4(b.hovercardShowUrls||[],b4),clickUrls:c4(l.loggingUrls||[],b4),visualElement:g.xF(b.trackingParams),productPrice:G,additionalFeesText:M,watchEndpoint:P||null}},gmb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:c4(a.impressionUrls||[],b4),elements:c4(a.elements||[],function(d,e){return fmb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.xF(a.trackingParams));return c},hmb=function(a){g.$V.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.iS(a)||g.kS(a);this.events=new g.RK(this);g.N(this,this.events);this.events.T(this.player,g.dK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.eK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Yb);this.events.T(window,"focus",this.cba);this.load();var b=g.If("STYLE");(g.xf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Rf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},imb=function(a){return a.player.getVideoData().Of?"current":a.Z?"new":"current"},d4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},jmb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=gmb(f,imb(a))));e4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Lx;d&&(c.postParams={ad_tracking:d});if(b=g.pTa(b))if(b=g.ye(b),b=g.ke(b))a.C=g.$B(b,c)},e4=function(a,b,c){c=void 0===c?!0:c;
a.player.Cf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&kmb(a);c=[];d=new g.cK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.V({I:"div",S:"ytp-ce-shadow"}),g.xU(a.player,a.B.element,4),a.D=new g.LG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=lmb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.xU(a.player,f.element,4);var h=new g.cK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);mmb(a,f,e)}else g.DF(new g.ZC("buildEndscreenElement null",
e))}a.player.yf(c);a.Yb()}},kmb=function(a){var b=g.yF(),c=g.zF();
c&&b&&a.endscreen.visualElement&&g.GB(g.MF)(void 0,c,b,a.endscreen.visualElement)},lmb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",La:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:f4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:g4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.ov(b.title||"")},ya:b.title},{I:"div",S:b.bE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",La:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:f4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:g4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.ov(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",La:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",La:["ytp-ce-channel-title","ytp-ce-link"],X:{href:g4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.ov(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",La:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:f4(b)}]};c=new g.V(c);var d=g.yf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Yu(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.HW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",La:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.ov(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",La:["ytp-ce-website-goto","ytp-ce-link"],X:{href:g4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:f4(b)},{I:"div",S:"ytp-ce-expanding-icon",X:nmb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",La:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.ov(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",La:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:g4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:f4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Yu(c.element,"ytp-ce-placeholder");return c},f4=function(a){if(a.jW)var b=a.jW.thumbnails;
return nmb(b?b[b.length-1].url:null)},nmb=function(a){return a?{style:"background-image: url("+a+")"}:{}},mmb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Yu(b.element,"ytp-ce-force-expand"),h4(a,c.id,!0)):(g.$u(b.element,"ytp-ce-force-expand"),g.$u(b.element,"ytp-ce-element-hover"),h4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){omb(a,b,c)});
b.Ta("mouseleave",function(){pmb(a,b,c)});
a.player.U().B||b.Ta("click",function(){g.Yu(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){qmb(a,c,m)});
b.Ta("keypress",function(m){qmb(a,c,m)});
b.Ta("focus",function(){omb(a,b,c)});
b.Ta("blur",function(){pmb(a,b,c)});
b.Ta("touchstart",function(){omb(a,b,c)});
var l=g.Af("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.$u(b.element,"ytp-ce-element-hover");g.$u(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Af("ytp-sb-subscribe",b.element));d(g.Af("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},qmb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Xu(d,"ytp-ce-element");){g.Xu(d,"subscribe-label")&&rmb(a,b);
if(g.Xu(d,"ytp-ce-channel-subscribe"))return;d=g.Sf(d)}if(!d||g.Xu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])pmb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Sca)rmb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ye(g4(a,b.targetUrl)),g.mH(g.ke(c),void 0,b.sessionData);else{var e=g.tS(a.player.U())||a.player.getVideoData().Of,f=function(){var h=g4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.LB(h);e&&n&&(n.v||
n.list)?a.player.Jo(n.v,l,n.list,!1,void 0,m||void 0):g.yxa(h,l)};
rmb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},g4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.AS(a)+b}else return"";return b},omb=function(a,b,c){g.Xu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Yu(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Qu(function(){g.Yu(b.element,"ytp-ce-element-hover")},200)).start():g.Yu(b.element,"ytp-ce-element-hover"),i4(a,c.g8),h4(a,c.id,!0))},pmb=function(a,b,c){g.$u(b.element,"ytp-ce-element-hover");
g.$u(b.element,"ytp-ce-force-expand");h4(a,c.id,!1)},h4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.bv(a.j[e].element,"ytp-ce-element-shadow-show",c)},i4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||d4(a))c&&c();else{b=smb(a,b);var e=0,f=!1,h=new g.Qu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.sE(b[a],d)}},rmb=function(a,b,c){i4(a,b.clickUrls,c);
(a=g.zF())&&b.t8&&g.TF(a,b.visualElement)},smb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(tmb(b[d],c));return a},tmb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},umb=function(a){return"string"===typeof a?a:""},j4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},vmb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},k4=function(a){return a.value?a.value:null},l4=function(a){if(!a)return null;
var b=g.ye(umb(a.value));b=g.ke(b);if(!b)return null;var c=j4(a.target,wmb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new vmb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},xmb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Amb=function(a){if(!a)return null;
var b=j4(a.type,ymb),c=j4(a.trigger,zmb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=l4(a?a:null);return b?new xmb(b,c,a):null},Bmb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Cmb=function(a,b){return g.Db(a.action,b)},Dmb=function(a,b){this.context=a;
this.j=b},Emb=function(a){return a.customMessage?m4("div","iv-card-message",a.customMessage):""},n4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Fmb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(m4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},m4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.ov(c);return{I:a,X:b,ya:c}},Gmb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.NC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.NC+");");c.dir=g.ov(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",La:b,X:c,V:d}},o4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.mj.click,5)}},Hmb=function(a,b){this.merchant=a;
this.price=b},Imb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Jmb=function(a,b){return b?b:Imb(a)?"current":"new"},p4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.tb=!1;this.Xa=new Map;this.fb=new Map;this.context.J.addEventListener(g.dK("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.eK("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},q4=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.zL(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.tb=!1});
a.context.j.Ta(b,"touchmove",function(){a.tb=!0})},Kmb=function(a){var b;
return(null==(b=g.U(a,g.yG))?0:b.url)?g.U(a,g.yG).url:(a=g.U(a,g.qT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},r4=function(a,b,c){return{MX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
q0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
OK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Lmb=function(a,b,c){p4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Gb=this.Na=this.Ob=this.C=this.isInitialized=!1;this.cards=[];this.ub=this.Z=this.Ma=this.G=this.Wa=this.j=null;this.ma=[];this.va=this.N=this.Lf=this.Ha=null;this.K=0;this.Ia=new g.Qu(function(){},c.W.Hl?4E3:3E3);
g.N(this,this.Ia);this.ib=new g.Qu(function(){});
g.N(this,this.ib);this.Ca=new Dmb(c,function(e,f,h,l,m,n){q4(d,e,f,h,l,m,n)});
this.Y=new g.V({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",La:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.Za=new g.LG(this.Y,330);g.N(this,this.Za);this.Nb=g.Af("iv-drawer-header-text",this.D);this.B=g.Af("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ob&&s4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ob=d.C)&&t4(d)});
this.Ra=new g.RK(this);g.N(this,this.Ra);this.J.addEventListener("videodatachange",this.Ys.bind(this))},Mmb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){s4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){t4(a)});
var c=b.headerText;g.Vf(a.Nb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ha=g.xF(b.trackingParams);a.N=g.xF(b.closeTrackingParams);a.Lf=g.xF(b.iconTrackingParams)},Nmb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.mG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,mj:{},hp:null,Oj:e.trackingParams?g.xF(e.trackingParams):null,Lf:f&&f.trackingParams?g.xF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
NC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};u4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.mG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:v4(a,c,b,f),sponsored:!1,mj:r4(f,e,f.command),hp:f.trackingParams?g.xF(f.trackingParams):null,Oj:e.trackingParams?g.xF(e.trackingParams):null,Lf:l&&l.trackingParams?g.xF(l.trackingParams):null,imageUrl:w4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.mG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,NC:null,title:f.title?g.mG(f.title):"",customMessage:f.callToAction?g.mG(f.callToAction):"",url:g.U(f.command,g.yG).url?l4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.yG).url}):null,onClickCommand:null};u4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.mG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:v4(a,c,b,e),sponsored:!1,mj:r4(e,f,e.endpoint),hp:e.trackingParams?g.xF(e.trackingParams):null,Oj:f.trackingParams?g.xF(f.trackingParams):null,Lf:l&&l.trackingParams?g.xF(l.trackingParams):null,channelId:g.U(e.endpoint,g.FT).browseId,customMessage:e.customText?g.mG(e.customText):null,profileImageUrl:w4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.mG(e.channelName):"",metaInfo:[e.subscriberCountText?g.mG(e.subscriberCountText):""],url:l4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.FT).canonicalBaseUrl?g.U(e.endpoint,g.FT).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.FT).browseId}),onClickCommand:null};u4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.mG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:v4(a,c,b,e),sponsored:!1,mj:r4(e,f,e.action),hp:e.trackingParams?g.xF(e.trackingParams):null,Oj:f.trackingParams?g.xF(f.trackingParams):null,Lf:l&&l.trackingParams?g.xF(l.trackingParams):null,fG:w4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.mG(e.customMessage):null,playlistVideoCount:g.mG(e.playlistVideoCount),title:e.playlistTitle?g.mG(e.playlistTitle):"",metaInfo:[e.channelName?g.mG(e.channelName):
"",e.videoCountText?g.mG(e.videoCountText):""],url:l4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Kmb(e.action)}),onClickCommand:null};u4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.mG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:v4(a,c,b,e),sponsored:!1,mj:r4(e,f,e.action),hp:e.trackingParams?g.xF(e.trackingParams):null,Oj:f.trackingParams?g.xF(f.trackingParams):null,Lf:l&&l.trackingParams?g.xF(l.trackingParams):null,fG:w4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.mG(e.lengthString):null,customMessage:e.customMessage?g.mG(e.customMessage):null,title:e.videoTitle?g.mG(e.videoTitle):"",metaInfo:[e.channelName?g.mG(e.channelName):
"",e.viewCountText?g.mG(e.viewCountText):""],isLiveNow:!!e.badge,url:l4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Kmb(e.action)}),onClickCommand:null};u4(a,b)}}}}}a.K++},w4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},v4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Pmb=function(a,b){if(b=Omb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Hf.id),g.Rf(b.SM),g.Ib(a.cards,b),a.bH(),x4(a)},s4=function(a,b,c){if(!a.C){a.Za.show();
a.Wa=new g.Qu(function(){g.Yu(a.context.J.getRootNode(),g.tZ.IV_DRAWER_OPEN)},0);
a.Wa.start();a.Ra.T(a.B,"mousewheel",function(h){a.Ia.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.zF();d&&a.Ha&&a.N&&g.RF(d,[a.Ha,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.DY||(f.DY=!0,Qmb(a.context.logger,f.Hf.mj.MX,b)),d&&g.RF(d,[f.Hf.hp]);V3(a.J);c&&(a.G=new g.Qu(function(){a.Ma=a.Z;a.ub.focus()},330),a.G.start())}},t4=function(a){a.C&&(a.Za.hide(),g.OC(a.Ra),g.$u(a.context.J.getRootNode(),g.tZ.IV_DRAWER_OPEN),a.C=!1,V3(a.J),a.G&&a.G.stop(),a.G=new g.Qu(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},Smb=function(a){g.Zu(a.Kb(),
[g.tZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.xU(a.J,a.D,5);Rmb(a);a.Z=g.Af("ytp-cards-button",a.J.getRootNode());a.ub=g.Af("iv-drawer-close-button",a.D);a.isInitialized=!0},Rmb=function(a){var b=g.Af("iv-drawer-close-button",a.D);
a.context.j.Ta(b,"click",a.P5,a);a.context.j.Ta(a.B,"touchend",function(){a.Ia.start()});
a.context.j.Ta(a.B,"scroll",a.n6,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Xu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.GE("iv-button-shown",a.L8,a));a.ma.push(g.GE("iv-button-hidden",a.K8,a));Tmb(a)},Tmb=function(a){a.ma.push(g.GE("iv-teaser-shown",a.n2,a));
a.ma.push(g.GE("iv-teaser-hidden",a.M8,a));a.ma.push(g.GE("iv-teaser-clicked",a.m2,a));a.Gb=!0},Umb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.sib))?void 0:c.targetId)?(a.va=b,!0):!1},Vmb=function(a,b){a.va=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.ORa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.r0a))?void 0:d.timeRangeStartMillis)||0,a.va=null,!0}return!1},u4=function(a,b){if(!Umb(a,b)||Vmb(a,b)){var c=Wmb(a,b);
if(c){var d={Hf:b,SM:c.element,DY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Gb||Tmb(a),Pmb(a,b.id),c=a.findLastIndex(d),g.Rb(a.cards,c,0,d));else{a.isInitialized||Smb(a);Pmb(a,b.id);var e=a.findLastIndex(d);g.Rb(a.cards,e,0,d);c.Ja(a.B,e);a.bH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,x4(a),Xmb(a,d),s4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Ymb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Ymb(a,d)}),x4(a))}}},Wmb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=Gmb(b);c={I:"div",La:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?k4(b.url)||"":""},V:[n4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[m4("h2",void 0,b.title),d]}]}]};c=new g.V(c);o4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",La:["iv-card","iv-card-channel"],V:[{I:"a",La:["iv-click-target"],X:{href:k4(b.url)||"","data-ytid":b.channelId},V:[n4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Emb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},Fmb(b)]}]}]};c=new g.V(c);o4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",La:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:k4(b.url)||""},V:[n4(b.fG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Emb(b),m4("h2","iv-card-primary-link",b.title),Fmb(b)]}]}]};
c=new g.V(c);o4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Gmb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?k4(b.url)||"":"";c={I:"div",La:c,X:{tabindex:"0"},V:[{I:"a",La:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[m4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.If("span");g.Vf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Ud(d,"adInfo");o4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",La:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",La:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:k4(c))||""},V:[n4(b.fG,d),{I:"div",S:"iv-card-content",V:[Emb(b),m4("h2","iv-card-primary-link",b.title),Fmb(b),f]}]}]};c=new g.V(e);o4(a,g.zf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Zmb=function(a){if(a.j)return"productListing"===a.j.Hf.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Fr(a.cards,function(c){return"productListing"===c.Hf.type})}return g.Fr(a.cards,function(c){return"productListing"===c.Hf.type})},x4=function(a){g.bv(a.J.getRootNode(),"ytp-cards-shopping-active",Zmb(a))},Ymb=function(a,b){if(!g.Xu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.zF(),d=a.j?a.j.Hf.Lf:a.Lf;
c&&d&&g.SF(c,[d]);a.j=b;x4(a)}(c=a.isInitialized&&"none"==a.Kb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.Hf.teaserDurationMs&&a.J.jB(!0,{teaserText:b.Hf.teaserText,durationMs:b.Hf.teaserDurationMs,onClickCommand:b.Hf.onClickCommand});a.ib.isActive()||((!a.C||!a.Ia.isActive()&&a.Na)&&Xmb(a,b),a.ib.start(910+b.Hf.teaserDurationMs))}},Xmb=function(a,b){a.Y.Jb?(b=new $3([0,
a.B.scrollTop],[0,b.SM.offsetTop],600,dmb),a.context.C.Ta(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ta(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.cG(a.Y,!0),a.B.scrollTop=b.SM.offsetTop,g.cG(a.Y,!1))},y4=function(a){return a.j&&a.j.Hf?a.j.Hf:a.cards[0]&&a.cards[0].Hf?a.cards[0].Hf:null},Omb=function(a,b){return g.Db(a.cards,function(c){return c.Hf.id===b})},z4=function(a,b,c){p4.call(this,a,b);
this.annotation=c;this.isActive=!1},$mb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},A4=function(a,b,c){z4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},anb=function(a,b){var c=void 0===c?0:c;
var d=Vlb(b).width;g.qs(b,d);c=new bmb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,cmb);g.N(a,c);a.context.C.Ta(c,"begin",function(){g.xs(b,!0)});
c.play()},dnb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
La:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",La:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.HW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",La:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",La:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.xs(h,!1);var l=a.createElement({I:"div",La:["branding-context-container-outer"]});l.appendChild(h);g.ks(l,"right",b.image_width+"px");g.Of(a.Kb(),l);a.C=new g.Qu(function(){bnb(a,h,l)},500);
g.N(a,a.C);a.context.j.Ta(a.Kb(),"mouseover",function(){cnb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Kb(),"mouseout",function(){a.C.start()})}},cnb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.ws(b);a.j||(b.style.width=g.ps(f.width,!0),c.style.width=g.ps(f.width,!0));g.ks(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ks(d,"right","1px");a.D=!0;g.xs(b,!0);a.G=new g.Qu(function(){g.Yu(this.Kb(),"iv-branding-active")},0,a);
a.G.start()}},bnb=function(a,b,c){g.$u(a.Kb(),"iv-branding-active");
a.K=new g.Qu(function(){g.xs(b,!1);a.j||(c.style.width=g.ps(0,!0))},250);
a.K.start();a.D=!1},enb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},fnb=function(a,b,c){z4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",La:["iv-promo-contents"]});this.G=new g.Qu(function(){d.j.setAttribute("aria-hidden","true");g.xs(d.C,!1);g.xs(d.B,!0)},700,this);
g.N(this,this.G)},inb=function(a,b,c){c.stopPropagation();
gnb(a);hnb(a,b);a.j.focus()},jnb=function(a){a.isCollapsed||a.Z||a.D||(g.Yu(a.Kb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},gnb=function(a){a.G.stop();
a.isCollapsed&&(g.av(a.Kb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.xs(a.B,!1),g.xs(a.C,!0))},hnb=function(a,b){a.D||(a.D=g.yg(function(){knb(this);
jnb(this)},b,a))},knb=function(a){a.D&&(g.Sa.clearTimeout(a.D),a.D=null)},lnb=function(a){this.J=a},Qmb=function(a,b,c){b&&(c?B4(a,b.map(function(d){return g.Fu(d,c)})):B4(a,b))},B4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.sE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},mnb=function(a){g.$V.call(this,a);
var b=this;this.ma=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new lnb(this.player);this.D=new g.RK(this);this.G=this.K=null;this.events=new g.RK(this);this.Zg=this.Y=this.j=null;this.va=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ra("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.o2,this);this.subscribe("resize",this.DJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.GZ,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.V({I:"div",La:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.xU(this.player,this.B.element,4);this.B.hide();this.C=new g.V({I:"div",La:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.Wt()&&this.load();var c=this.createElement({I:"style"});(g.xf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Rf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},nnb=function(a){a=a.createElement({I:"div",
La:["annotation","annotation-type-custom"]});g.xs(a,!1);return a},onb=function(a,b){b=!b.isCued()&&!g.SG(b,1024);
g.cG(a.B,b);g.cG(a.C,b)},pnb=function(a,b,c){a.Z=!0;
a.G=g.$B(b,c)},qnb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(qnb(a,e))}return c},unb=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.TB(h)&&h.responseXML?h.responseXML:null)&&rnb(a,h)}};
g.gD()&&(d.onFinish=snb(a,d.onFinish));d.postParams={ic_only:"1"};tnb(d,c);a.Z=!0;g.$B(b.Wa,d)}}},tnb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.gH&&(a.postParams.ic_coll=b.gH);b.TM&&(a.postParams.ic_xml=b.TM);b.TK&&(a.postParams.ic_track=b.TK)},vnb=function(a){var b=new g.V({I:"div"});
g.xs(b.element,!1);var c=new Lmb(a.player,b.element,C4(a));g.N(c,b);b.Ja(a.B.element);c.PF();return c},xnb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ma=!0,wnb(a,b),b.headerText&&a.Zg&&(c=g.mG(b.headerText),a.Zg.setAttribute("title",c))},C4=function(a){if(!a.Y){var b=new emb(a);
g.N(a,b);var c=new g.Ep(a);g.N(a,c);a.Y=new enb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.zj)}return a.Y},rnb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.zF();if(e){var f=g.yF();f&&g.GB(g.Xva)(void 0,e,f,[g.xF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=qnb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=j4(f.type,ynb),p=j4(f.style,znb),q=umb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Amb;if(null==t)var v=null;else if(g.ab(t)){l=[];for(var x=g.u(t),A=x.next();!A.done;A=x.next()){var E=f(A.value);
E&&l.push(E)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Bmb(m,n,p,v,r):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=nnb(f),M=null;switch(l.type){case "branding":if(f.player.U().Fe)break;f.B.element.appendChild(G);M=new A4(G,C4(f),l);break;case "promotion":g.xU(f.player,G,4),M=new fnb(G,C4(f),l)}M&&M.PF();if(f=M)g.N(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=vnb(a),g.N(a,a.j));if("card"===e.type){G=a.j;var P=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(P)switch(f=e.tracking||{},f={MX:f.impression,click:f.click,close:f.close,q0:f.teaser_impression,OK:f.teaser_click},l=e.tracking_params||{},M=null,P){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,hp:l.card?g.xF(l.card):null,Oj:l.teaser?g.xF(l.teaser):null,Lf:l.icon?g.xF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:l4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};u4(G,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,
hp:l.card?g.xF(l.card):null,Oj:l.teaser?g.xF(l.teaser):null,Lf:l.icon?g.xF(l.icon):null,fG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:l4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};u4(G,c);break;case "productListing":e.signin_url&&(M=l4({target:"current",value:e.signin_url}));P=[];for(var R=e.offers||[],ba=0;ba<R.length;ba++)P.push(new Hmb(g.gf(R[ba].merchant),
g.gf(R[ba].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,hp:l.card?g.xF(l.card):null,Oj:l.teaser?g.xF(l.teaser):null,Lf:l.icon?g.xF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,NC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:l4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Eob:M,Dob:e.signin_title?e.signin_title:void 0,Cob:e.signin_message?e.signin_message:void 0,offers:P,onClickCommand:null};u4(G,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,hp:l.card?g.xF(l.card):
null,Oj:l.teaser?g.xF(l.teaser):null,Lf:l.icon?g.xF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,NC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:l4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};u4(G,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,hp:l.card?g.xF(l.card):null,Oj:l.teaser?g.xF(l.teaser):null,Lf:l.icon?g.xF(l.icon):null,fG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:l4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},u4(G,c)}}else Mmb(a.j,e);c=!0}}c&&
(V3(a.player),a.DJ())},wnb=function(a,b){var c=!1;
a.j||(a.j=vnb(a),g.N(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Nmb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.MT(f)||(c=a.j,d=b.headerText?g.mG(b.headerText):"",g.Vf(c.Nb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ha=b.trackingParams?g.xF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.xF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Lf=b.icon.infoCardIconRenderer.trackingParams?g.xF(b.icon.infoCardIconRenderer.trackingParams):null,a.DJ());V3(a.player)}},Anb=function(a,b,c,d,e){if(!a.player.U().Fe){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.FT)&&g.U(b.navigationEndpoint,g.FT).browseId&&f.push(new xmb("openUrl","click",new vmb("/channel/"+g.U(b.navigationEndpoint,g.FT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.GT)){d.channel_id=g.U(b.subscribeButton,g.GT).channelId;var l;b=g.U(b.subscribeButton,g.GT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.mG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.mG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.mG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.mG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.Q2))?void 0:m.url)||"";l={subscribeText:g.mG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.mG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Bmb(c,"branding","branding",f,d);l=nnb(a);a.B.element.appendChild(l);f=new A4(l,C4(a),f);f.PF();g.N(f,f);a.N[c]=f}},snb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.va.push(g.Iu.Xi(function(){b.apply(null,g.pa(c))}))}},Bnb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.qU.prototype.jB=g.fa(29,function(a,b){var c=g.pW(this.Bb());c&&c.jB(a,b)});
var X3={},Y3=null;g.ob($3,g.cv);g.k=$3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;Z3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.uJ();this.Xl("play");this.isPaused()&&this.Xl("resume");this.j=1;var b=g.fb(this);b in X3||(X3[b]=this);Ylb();Zlb(this,a);return!0};
g.k.stop=function(a){Z3(this);this.j=0;a&&(this.progress=1);$lb(this,this.progress);this.Xl("stop");this.ir()};
g.k.pause=function(){this.isPlaying()&&(Z3(this),this.j=-1,this.Xl("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Xl("destroy");$3.Uf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.yL=function(){this.Xl("animate")};
g.k.Xl=function(a){this.dispatchEvent(new amb(a,this))};
g.ob(amb,g.Ab);g.ob(a4,$3);a4.prototype.C=function(){};
a4.prototype.yL=function(){this.C();a4.Uf.yL.call(this)};
a4.prototype.ir=function(){this.C();a4.Uf.ir.call(this)};
a4.prototype.uJ=function(){this.C();a4.Uf.uJ.call(this)};
g.ob(bmb,a4);bmb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(emb,g.I);g.k=emb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.IC(a,b,c);this.j.push(a);return a};
g.k.UI=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=Wlb(a,b,c);this.j.push(a);return a};
g.k.Tc=function(a){g.JC(a);g.Ib(this.j,a)};
g.k.Tf=function(){g.JC(this.j);this.j.length=0};
g.k.xa=function(){this.Tf();g.I.prototype.xa.call(this)};g.w(hmb,g.$V);g.k=hmb.prototype;g.k.load=function(){g.$V.prototype.load.call(this);if(!d4(this)){var a=g.qTa(this.player.getVideoData());a?(a=gmb(a,imb(this)),e4(this,a,!1)):jmb(this)}};
g.k.unload=function(){e4(this,null);this.C&&(this.C.abort(),this.C=null);g.$V.prototype.unload.call(this)};
g.k.Lh=function(a,b){return d4(this)?"loadCustomEndscreenRenderer"===a?(a=gmb(b,"new"),e4(this,a),!0):null:null};
g.k.getOptions=function(){return d4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Cnb.length;f++){var h=Math.abs(b.width-Cnb[f]);if(-1===e||d>=h)e=f,d=h}d=Dnb[e];this.B&&g.ks(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.vs(e.element,m,f);g.qs(e.element,n,p);g.av(e.element,Enb);256<m||256<f?g.Yu(e.element,"ytp-ce-large-round"):96<m||96<f?g.Yu(e.element,"ytp-ce-medium-round"):g.Yu(e.element,"ytp-ce-small-round");g.av(e.element,Fnb);m=h.left+h.width/2;h=h.top+l/2;g.Yu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.av(e.element,Dnb);g.Yu(e.element,d);(e=g.yf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ks(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())i4(this,this.endscreen.impressionUrls),(a=g.zF())&&this.endscreen.visualElement&&g.QF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Yu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Yu(b,"ytp-ce-shown");i4(this,c.impressionUrls);(b=g.zF())&&g.QF(b,c.visualElement);this.player.U().K&&this.player.ob("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.$u(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.$u(b,"ytp-ce-shown");this.player.U().K&&this.player.ob("endscreenelementhidden",a)}};
g.k.cba=function(a){var b=this;a.target===window&&(new g.Qu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.av(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Cnb=[346,426,470,506,570,640,853,1280,1920],Dnb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Fnb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Enb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var wmb={yua:"current",oVa:"new"};var ymb={CLOSE:"close",fZa:"openUrl",SUBSCRIBE:"subscribe"},zmb={Gsa:"click",CLOSE:"close",vGa:"hidden",h4a:"rollOut",i4a:"rollOver",W5a:"shown"};Bmb.prototype.Ue=function(){var a=Cmb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var znb={ina:"anchored",G1:"branding",CHANNEL:"channel",oua:"cta",yGa:"highlightText",zKa:"label",PLAYLIST:"playlist",N0a:"popup",W8a:"speech",SUBSCRIBE:"subscribe",Mbb:"title",VIDEO:"video",mjb:"website"},ynb={G1:"branding",nqa:"card",zwa:"drawer",xGa:"highlight",LQa:"marker",u2a:"promotion",TEXT:"text",Rkb:"widget"};g.w(p4,g.I);g.k=p4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.cK(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.fb.set(a,e);this.context.J.yf([a])};
g.k.PF=function(){this.context.B.subscribe("resize",this.bH,this)};
g.k.Kb=function(){return this.element};
g.k.zL=function(a,b,c,d,e,f){if(this.tb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Rf(this.Kb())};
g.k.bH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=k4(a);if(f){var h=Jmb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Of||!1,n=g.LB(f||"");m&&n&&(n.v||n.list)?e.context.J.Jo(n.v,b,n.list,!1):g.mH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);B4(this.context.logger,c,l,d);Imb(f)||(c=g.zF(),d=b.itct,c&&d&&g.TF(c,g.xF(d)))}};
g.k.xa=function(){this.Xa.clear();this.fb.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.N(this,a);return a.element};g.w(Lmb,p4);g.k=Lmb.prototype;g.k.Ys=function(){this.va&&u4(this,this.va)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.ws(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.bH=function(){var a=this.isAvailable();g.xs(this.Kb(),a);g.bv(this.context.J.getRootNode(),g.tZ.IV_DRAWER_ENABLED,a);V3(this.J)};
g.k.destroy=function(){this.J.jB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.HE(this.ma);g.OC(this.Ra);this.Wa&&this.Wa.dispose();this.G&&this.G.dispose();p4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.Hf.startMs>c.Hf.startMs||a.Hf.startMs===c.Hf.startMs&&a.Hf.timestamp>=c.Hf.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.P5=function(){if(this.C){B4(this.context.logger,y4(this).mj.close);var a=g.zF();a&&this.N&&g.TF(a,this.N);t4(this)}};
g.k.n6=function(){g.bv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.L8=function(){var a=g.zF(),b=y4(this);b=b?b.Lf:this.Lf;a&&b&&g.RF(a,[b])};
g.k.K8=function(){var a=g.zF(),b=y4(this);b=b?b.Lf:this.Lf;a&&b&&g.SF(a,[b])};
g.k.n2=function(){var a=y4(this);B4(this.context.logger,a.mj.q0);var b=g.zF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Oj&&c.push(a.Oj);a.Lf&&c.push(a.Lf);0<c.length&&g.RF(b,c)}else g.RF(b,[a.Oj,a.Lf])};
g.k.M8=function(){var a=g.zF(),b=y4(this);a&&b&&g.SF(a,[b.Oj])};
g.k.m2=function(a){var b=y4(this),c=g.zF();this.j?a?(a=this.context.logger,B4(a,b.mj.OK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Oj&&g.TF(c,b.Oj)):(a=this.context.logger,B4(a,b.mj.OK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Lf&&g.TF(c,b.Lf)):(a=this.context.logger,B4(a,b.mj.OK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Lf&&g.TF(c,this.Lf))};g.w(z4,p4);z4.prototype.PF=function(){p4.prototype.PF.call(this);$mb(this)};
z4.prototype.show=function(){p4.prototype.show.call(this);var a=g.zF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.RF(a,[g.xF(b.itct)])};
z4.prototype.hide=function(){p4.prototype.hide.call(this);var a=g.zF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.SF(a,[g.xF(b.itct)])};g.w(A4,z4);A4.prototype.cB=function(){g.Yu(this.Kb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",La:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.xs(this.B,!1);var b=this.createElement({I:"button",La:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Kb().appendChild(b);var c=this.annotation.Ue();c&&q4(this,b,c,this.annotation.id,a.session_data);dnb(this,a)};
A4.prototype.show=function(){if(!this.isActive&&(z4.prototype.show.call(this),this.N||(this.cB(),this.N=!0),g.xs(this.Kb(),!0),this.isActive=!0,this.B)){try{anb(this,this.B)}catch(a){}g.Yu(this.context.J.getRootNode(),"ytp-branding-shown")}};
A4.prototype.hide=function(){this.isActive&&(z4.prototype.hide.call(this),g.xs(this.Kb(),!1),this.isActive=!1,g.$u(this.context.J.getRootNode(),"ytp-branding-shown"))};
A4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);z4.prototype.destroy.call(this)};g.w(fnb,z4);g.k=fnb.prototype;
g.k.cB=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Kb().setAttribute("aria-hidden","true");this.Kb().setAttribute("aria-label","Promotion");this.Kb().tabIndex=0;var e=this.annotation.Ue(),f=b.image_url;if(f){var h=this.createElement({I:"div",La:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&q4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Se(f,k4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",La:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",La:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&q4(this,
this.Kb(),e,this.annotation.id,b.session_data,void 0,c)}g.Yu(this.j,"iv-click-target");e&&q4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",La:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.Yu(this.j,"iv-click-target"),e&&q4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",La:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ta(this.B,"click",function(q){inb(a,5E3,q)});
c.appendChild(this.B);g.xs(this.B,!1);this.context.j.Ta(this.Kb(),"mouseover",this.G7,this);this.context.j.Ta(this.Kb(),"mouseout",this.F7,this);this.context.j.Ta(this.Kb(),"touchend",function(q){inb(a,5E3,q)});
this.C=this.createElement({I:"button",La:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ta(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.B7:this.A7,this);c.appendChild(this.C);g.Zu(this.Kb(),d);h&&(g.Of(this.Kb(),h),n&&h.appendChild(n));g.Of(this.Kb(),this.N);g.Of(this.Kb(),c)};
g.k.show=function(){this.isActive||(z4.prototype.show.call(this),this.Y||(this.cB(),this.Y=!0),g.xs(this.Kb(),!0),g.yg(function(){g.$u(this.Kb(),"iv-promo-inactive")},100,this),this.Kb().removeAttribute("aria-hidden"),this.isActive=!0,knb(this),gnb(this),hnb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Yu(this.Kb(),"iv-promo-inactive"),this.isActive=!1,this.Kb().setAttribute("aria-hidden","true"))};
g.k.zL=function(a,b,c,d,e,f){return this.isCollapsed?!1:z4.prototype.zL.call(this,a,b,c,d,e,f)};
g.k.G7=function(a){this.Z=!0;inb(this,500,a)};
g.k.F7=function(){this.Z=!1;jnb(this)};
g.k.A7=function(a){a.stopPropagation();this.hide()};
g.k.B7=function(a){a.stopPropagation();knb(this);this.isCollapsed=!0;g.Yu(this.Kb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();z4.prototype.destroy.call(this)};g.w(mnb,g.$V);g.k=mnb.prototype;g.k.Lh=function(a,b){if(!Bnb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.w2(b))&&rnb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Pmb(this.j,b),V3(this.player)),!0}return null};
g.k.getOptions=function(){return Bnb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Wt=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.$T(b)||g.jU(this.player.app)?!1:1===c&&!b.ZU||a.Na.get(b.videoId)||g.NT(b)||g.rTa(b)?!0:!1};
g.k.DJ=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.vs(this.C.element,a.width,a.height);g.qs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.zn();a=this.j;b=b.width;g.bv(a.D,"iv-drawer-small",426>=b);g.bv(a.D,"iv-drawer-big",1280<=b)}};
g.k.o2=function(a){onb(this,a.state);g.SG(a.state,2)&&(this.Mk()&&this.Zo()&&2!==this.player.getPresentingPlayerType()&&this.kB(!1),this.jB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.TB(h)&&h.responseXML?h.responseXML:null)&&(rnb(b,h),g.Yu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.$V.prototype.load.call(this);onb(this,this.player.Xb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.gD()&&(a=snb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&tnb(e,f);f=f&&(f.TM||f.gH);if(!c.Fx||f)c.Wa?pnb(this,c.Wa,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.MT(h))&&!b.ma&&xnb(b,h)},this.player.addEventListener("videodatachange",this.K));
g.xU(this.player,this.C.element,4);this.DJ();(f=g.NT(c))&&wnb(this,f);(f=g.rTa(c))&&f.featuredChannel&&Anb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Zg=g.Af("ytp-cards-button",this.player.getRootNode());g.MT(c)&&xnb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&pnb(this,b.Wa,a)};
g.k.unload=function(){this.player.Cf("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,V3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.ma=!1;this.N={};this.B.hide();g.$V.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.GZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?unb(this):this.load())};
g.k.Mk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ma};
g.k.Zo=function(){return!!this.j&&this.j.C};
g.k.kB=function(a,b,c){b=void 0===b?!1:b;this.Mk();this.j&&(a?c?s4(this.j,c,b):s4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):t4(this.j))};
g.k.jB=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.GZ,this);g.$u(this.player.getRootNode(),g.tZ.IV_DRAWER_OPEN);for(var a=this.va,b=g.Iu,c=0,d=a.length;c<d;c++)b.Sj(a[c]);this.va.length=0;g.$V.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.N(this,a);return a.element};g.ZV("annotations_module",mnb);g.ZV("creatorendscreen",hmb);})(_yt_player);
