(function(g){var window=this;'use strict';var Inb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Jnb=function(a,b){var c=new g.HS;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Knb=function(a,b){var c,d,e;
return g.H(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.RD(),2);if(3!=f.j){d=f.B;if(!d)throw g.uD("gct");return g.z(f,g.WS(d),3)}e=f.B;return f.return(e.get("captions",c))})},Lnb=function(a,b,c){Knb(a,b).then(function(d){d&&c(d.trackData,new g.HS(d.metadata))})},Onb=function(a){if(!Mnb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Nnb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Pnb=function(){return g.SC("yt-player-caption-display-settings")},D4=function(){this.segments=[]},Qnb=function(a,b){var c=g.Tb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Hb(a.segments,c),g.Hb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Rb(a.segments,c,0,b),g.Rb(a.segments,c+1,0,b)))},Rnb=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.ma=c;this.Z=d;this.G=e;this.Y=f;this.D=new D4;this.K=-1;this.C=this.B=this.j=null;this.N=new g.Qu(this.wY,1E3,this);this.events=new g.RK(this);g.N(this,this.N);g.N(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.HA);this.HA();this.wY()},Snb=function(a){return a.j&&a.j.D?a.j.D+a.player.Vc()<a.player.getCurrentTime():!1},Tnb=function(a,b){var c=g.rOa(b,a.policy,{}).Ue(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ca){d.method="POST";var e=b.D,f=(0,g.TZ)([120,0]);e&&g.PO(e,g.LUa);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.cC(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.B){var l=!(a.G?h.response:h.responseText)||400<=h.status,m=g.gPa(h);if(m){h=g.rOa(a.B,a.policy,{});a.B.Tk(h,m);Tnb(a,a.B);break a}l?a.player.qa("capfail",{status:h.status}):(a.player.Ei().gi("fcb_r"),m=a.B.eb[0].Pa,null!=a.Z&&a.K!==m&&(l=a.B.eb[0],a.G?a.Z(h.response,1E3*(l.startTime+a.player.Vc())):
a.Z(h.responseText,1E3*(l.startTime+a.player.Vc())),a.K=m))}a.B=null;a.C=null}}).zl(function(h){a.B=null;
a.C=null;var l;a.player.qa("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.B=b;Qnb(a.D,a.B.eb[0].Pa)},E4=function(a,b){g.cW.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.G=!1;this.K=g.FJ(this.J.U())&&!this.j.isManifestless},Vnb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.BXa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Glb.get(e);null==q&&(q=Unb[e]||Unb[e.replace(/-/g,"_")],g.Glb.set(e,q));h=q||h}c.push(new g.HS({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Wnb=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},Xnb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.BXa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},Ynb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in g.Ulb?g.Ulb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={iE:c.iE};c.iE=d;var e=function(f){return function(){return String(a[f.iE])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.iE+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.iE,"gi"),e)}return b},F4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.cf);a.params.cf&&Object.assign(r,a.params.cf);Object.assign(r,c.cf);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.cf=r;var t=1===q.Ri,v=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],x,A,E;(l=l.kb("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(A=x.captions)?void 0:null==(E=A.playerCaptionsTracklistRenderer)?void 0:E.openTranscriptCommand))&&
v.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":Ynb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.V.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:v});var F=
this;this.K=[];this.Ha=!1;this.B=a;this.Na=this.Ma=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=q;this.Jc=c;this.va=b;this.D=this.Fa("captions-text");this.Vb=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Wa=Znb(d,e,f,h);this.Lc=m;l&&(this.G=this.Fa("caption-edit"),this.T(this.G,"click",function(){F.Lc()}));
this.type=0;this.fb=this.Wa*$nb(r);this.Gb=p;a=new g.zV(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.t2,this);a.subscribe("dragmove",this.s2,this);a.subscribe("dragend",this.q2,this);this.ib=this.Za=this.ub=this.tb=0;a="";this.j.windowOpacity&&(a=Onb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":aob[this.j.textAlign]};this.Vb&&(b["border-radius"]=a?this.fb/8+"px":"");(this.C=
2===this.B.params.Ri||3===this.B.params.Ri)&&bob(this,this.element);g.ks(this.element,b);if(p){var G;null==(G=this.element.parentElement)||G.style.setProperty("--caption-window-color",a)}switch(this.j.Tl){case 0:case 1:case 2:g.Yu(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Yu(this.element,"ytp-caption-window-bottom")}},bob=function(a,b){var c="vertical-rl";
1===a.j.hS&&(c="vertical-lr");g.Cf&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.ks(b,"-o-writing-mode",c);g.ks(b,"-webkit-writing-mode",c);g.ks(b,"writing-mode",c);g.ks(b,"text-orientation","upright");g.Yu(b,"ytp-vertical-caption");3===a.B.params.Ri&&(g.ks(b,"text-orientation",""),g.ks(b,"transform","rotate(180deg)"))},$nb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},cob=function(a,b){var c={},d=b.background?b.background:a.j.cf.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.cf.backgroundOpacity;d=Onb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Vb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Wa*$nb(b)+"px";d=1;e=b.color||a.j.cf.color;if(b.color||null!=b.textOpacity)e=Onb(e),d=null==b.textOpacity?a.j.cf.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.UM&&(h=e=b.UM);var l=a.Wa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.mC()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.cf.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.d8&&(c.visibility="hidden");1===b.KX&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.wS||g.tD,3===a.B.params.Ri?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Ao||2===b.Ao||3===b.Ao||4===b.Ao||5===b.Ao)if(g.wS)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ao){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},G4=function(a){a=a.split("px");
return 0<a.length?(a=Number(a[0]))?a:0:0},dob=function(a){a.N=g.If("SPAN");
g.ks(a.N,{display:"block"});g.Yu(a.N,"caption-visual-line");a.D.appendChild(a.N)},eob=function(a,b){var c=g.If("SPAN");
g.ks(c,{display:"inline-block","white-space":"pre-wrap"});g.ks(c,cob(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.ks(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ks(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},fob=function(a,b,c){a.Ha=a.Ha||!!c;
var d={};Object.assign(d,a.j.cf);Object.assign(d,c||b.j);Object.assign(d,a.Jc.cf);(c=!a.N)&&dob(a);for(var e=a.Ma&&a.Na&&g.od(d,a.Na)?a.Ma:eob(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(dob(a),e=eob(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Nf(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.wS||!g.ms(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.ms(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Vc?g.ks(e,m,"1em"):g.ks(e,m,"0.5em")))}a.Na=d;a.Ma=e;a.K.push(b)},Znb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},hob=function(){this.C=this.time=this.mode=this.B=0;
this.D=new gob(this);this.G=new gob(this);this.j=[];this.clear()},job=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Uu:a,
qs:b,result:0};a=iob[a];b=iob[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ke()&&c.qs===d;if(d)return{Uu:a,qs:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Uu:a,qs:b,result:2};return{Uu:a,qs:b,result:3}},lob=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,kob(a.D,b,c,d))},mob=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.u(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?lob(a,d.HV,d.IV,b):1===d.type&&a.B&496&&kob(a.G,d.HV,d.IV,b);a.j.length=0},H4=function(){this.type=0},I4=function(){this.state=this.qs=this.Uu=0},nob=function(){this.timestamp=this.j=0},J4=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new H4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new nob}},K4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},sob=function(a,b){switch(a){case 0:return oob[(b&127)-32];
case 1:return pob[b&15];case 2:return qob[b&31];case 3:return rob[b&31]}return 0},L4=function(a){return a.B[a.row][a.col]},M4=function(a,b,c){2<=b&&1<a.col&&(--a.col,L4(a).j=0);
var d=L4(a);d.timestamp=a.D.time+0;d.j=sob(b,c);32>a.col&&a.col++},tob=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},N4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},uob=function(a){a.row=0<a.j?a.j:1;
a.col=1;N4(a,0,15)},vob=function(a){this.C=a;
this.G=0;this.style=new H4;this.K=new J4(this.C);this.N=new J4(this.C);this.text=new J4(this.C);this.B=this.K;this.D=this.N;this.j=this.B},wob=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(K4(d,c),uob(a.B),uob(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(K4(d,c),N4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},xob=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},yob=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},gob=function(a){this.j=a;
this.G=0;this.C=new vob(this.j);this.K=new vob(this.j);this.B=new I4;this.D=this.C},kob=function(a,b,c,d){a.B.update();
b=job(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Uu;c=b.qs;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&M4(a,0,b),c&96&&M4(a,0,c),0!==b&&0!==c&&3===a.style.type&&K4(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Uu=e,b.qs=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(4!==b.style.type?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;tob(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));N4(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:M4(b.j,0,32);break a;case 48:57===c?(d=b.j,L4(d).j=0,32>d.col&&d.col++):M4(b.j,1,c&15)}break;case 2:c&32&&M4(b.j,2,c&31);break;case 3:c&32&&M4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:xob(b);
break;case 33:d=b.j;1<d.col&&(--d.col,L4(d).j=0);break;case 36:d=b.j;b=L4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:wob(b,2,d);break;case 38:wob(b,3,d);break;case 39:wob(b,4,d);break;case 40:M4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);uob(d);yob(b);break;case 43:yob(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:K4(a,
d)}N4(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.col=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;K4(a,d);tob(a,b,b+1,a.j-1);N4(a,a.row,1)}break;case 46:N4(b.D,0,15);break;case 47:K4(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,xob(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.col+=c&3)&&(d.col=32)}}},zob=function(){},O4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.cK.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Bob=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.pg){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Aob(l.textContent,n.textContent,p.textContent,f.textContent,h);return new O4(a,b,e,c,l,d,m)}switch(m.pg){case 9:case 10:m.Ao=1;break;case 11:m.Ao=2;break;case 12:m.Ao=3;break;case 13:m.Ao=4;break;case 14:m.Ao=5}return new O4(a,b,e,c,l.textContent||"",d,m)},Aob=function(a,b,c,d,e){var f=g.mC(),h=
f?g.If("DIV"):g.If("RUBY"),l=g.If("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.If("DIV"):g.If("RP");a.textContent=b;h.appendChild(a);b=f?g.If("DIV"):g.If("RT");b.textContent=c;h.appendChild(b);c=e.pg;if(10===c||11===c||12===c||13===c||14===c)if(g.ks(b,"text-emphasis-style","filled circle"),g.ks(b,"text-emphasis-color","currentcolor"),g.ks(b,"webkit-text-emphasis","filled circle"),11===e.pg||13===e.pg)g.ks(b,"webkit-text-emphasis-position","under left"),g.ks(b,"text-emphasis-position","under left");c=!0;if(4===e.pg||7===e.pg||12===e.pg||
14===e.pg)g.ks(h,"ruby-position","over"),g.ks(h,"-webkit-ruby-position","before");else if(5===e.pg||6===e.pg||11===e.pg||13===e.pg)g.ks(h,"ruby-position","under"),g.ks(h,"-webkit-ruby-position","after"),c=!1;e=f?g.If("DIV"):g.If("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.ks(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.ks(f,"display","none"),f=f.nextElementSibling,g.ks(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ks(h.lastElementChild,"display","none"),d?(g.ks(h,"padding-top","0.6em"),g.ks(f,"top","0")):(g.ks(h,"padding-bottom","0.6em"),g.ks(f,"bottom","0")));return h},P4=function(){g.I.apply(this,arguments)},Q4=function(a,b,c,d,e){g.cK.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Cob=function(a){var b="_"+R4++;
return new Q4(0,0x8000000000000,0,b,a)},S4=function(a){P4.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+R4++;this.K={};this.B=this.j=null;this.G=!0},T4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},U4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},V4=function(a,b){a=T4(a,b);
return void 0!==a?a:null},X4=function(a,b){a=a.getAttribute(b);
if(null!=a)return W4.test(a),a},Dob=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=V4(b,"mh");null!=a&&(c.sA=a);a=V4(b,"ju");null!=a&&(c.textAlign=a);a=V4(b,"pd");null!=a&&(c.Ri=a);a=V4(b,"sd");null!=a&&(c.hS=a);a=X4(b,"wfc");null!=a&&(c.windowColor=a);b=T4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Eob=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=V4(b,"ap");null!=a&&(c.Tl=a);a=T4(b,"cc");null!=a&&(c.ys=a);a=T4(b,"ah");null!=a&&(c.nk=a);a=T4(b,"rc");null!=a&&(c.zr=a);b=T4(b,"av");null!=b&&(c.Bo=b);return c},Fob=function(a,b,c,d){var e={};
Object.assign(e,Eob(a,b));Object.assign(e,Dob(a,b));d?g.od(e,a.C)?(d=a.D,e=a.C):d="_"+R4++:d=b.getAttribute("id")||"_"+R4++;a=T4(b,"t")+c;b=T4(b,"d")||0x8000000000000;if(2===e.Ri||3===e.Ri)c=e.zr,e.zr=e.ys,e.ys=c;return new Q4(a,b,0,d,e)},Y4=function(a){P4.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},Z4=function(a){a=g.He(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Gob=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.zr=a);b=b.ccColCount;void 0!==b&&(f.ys=b);if(2===f.Ri||3===f.Ri)b=f.zr,f.zr=f.ys,f.ys=b;return new Q4(c,d,0,e,f)},$4=function(a,b,c,d){g.cW.call(this,a);
this.videoData=b;this.audioTrack=c;this.Va=d;this.D=b.Bu},a5=function(a,b,c,d,e,f,h,l,m,n){F4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},b5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},c5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},d5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},e5=function(a,b){P4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new hob;this.j.B=1<<this.track},Iob=function(a){if("string"===typeof a)return!1;
a=new b5(a,8,0);return Hob(a)},Hob=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==d5(a))return!1;
a.version=c5(a);if(1<a.version)return!1;c5(a);c5(a);c5(a);return!0},f5=function(a,b,c,d,e,f,h,l,m,n){F4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ca=[];this.ma=this.Y=this.Ra=0;this.Ia=NaN;this.Ob=0;this.jc=null;this.Xa=new g.Qu(this.haa,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.zV(this.element,!0),g.N(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.Yu(this.element,"ytp-caption-window-rollup");g.N(this,this.Xa);g.ks(this.element,"overflow","hidden")},Job=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.hS&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Kob=function(a){a.Ca=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.zr,c=0,d=0,e=a.Ca.length-1;c<b&&-1<e;){var f=a.Ca[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Y=d;b=Math;c=b.max;isNaN(a.Ia)&&((d=a.j.ys)?(e=g.If("SPAN"),g.Vf(e,"\u2013".repeat(d)),g.ks(e,cob(a,a.j.cf)),a.D.appendChild(e),a.Ia=e.offsetWidth,a.D.removeChild(e)):a.Ia=0);d=a.D;a.ma=c.call(b,a.Ia,a.Ob,(a.C?d.offsetHeight:d.offsetWidth)+1)},Lob=function(a,b){Kob(a);
var c=a.Ca.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Y-c;if(c!==a.Ra){var d=0<c&&0===a.Ra,e=c<a.Ra;b||isNaN(c)||d||!e||(g.Yu(a.element,"ytp-rollup-mode"),g.Ru(a.Xa));g.ks(a.D,"transform",Job(a,c));a.Ra=c}Kob(a)},g5=function(){P4.call(this)},Mob=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new O4(b,c,d,e.id,p.nodeValue,f||0<n,g.md(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Mob(a,b,c,d,e,!0,p,q,m)}}},Nob=function(a){var b=a.split(":");
a=0;b=g.u(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Oob=function(a,b,c,d){d=Object.assign({sA:0},d);
return new Q4(a,b,c,"_"+R4++,d)},h5=function(a,b){g.I.call(this);
this.J=a;this.W=b;this.j=null;this.B=this.J.zz()},Pob=function(a){if("string"===typeof a||Iob(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.jQ(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.uO(a)},Rob=function(a,b,c){if("string"===typeof b||Iob(b))return[{trackData:b,
bS:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.ONa(d);if(a.B&&e){var f=g.FNa(e),h=g.GNa(e);e=e.j;f&&e&&a.B.mG(e,f,h)}a=g.qQ(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.uO(e),f.push({trackData:e,bS:c+1E3*h});Qob(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Qob=function(a,b,c){var d=g.jQ(a,0,1836476516),e=9E4;
d&&(e=g.kQ(d)||9E4);d=0;for(var f=g.qQ(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.jQ(a,l.dataOffset,1953653094))&&(l=g.jQ(a,l.dataOffset,1952867444))&&(l=g.LNa(l)/e*1E3,0===h&&(d=l),b[h].bS=l-d+c||c*h*1E3)}},Sob=function(a,b,c,d,e){if(!Iob(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new e5(e,b));return a.j.Wn(c,d)},Tob=function(a,b,c){a.j||(a.j=new g5);
a=a.j.Wn(b,c);.01>Math.random()&&g.DF(Error("Deprecated subtitles format in web player: WebVTT"));return a},Vob=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new Y4(Uob(b))),a.j.Wn(c,d)}catch(f){return g.CF(f),[]}var e=g.w2(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new S4(Uob(b),a.W)),a.j.Wn(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Uob=function(a){var b=
{};
if(a=g.KS(a))b.lang=a,g.Qhb.test(a)&&(b.Ri=1);return b},i5=function(a){g.$V.call(this,a);
var b=this;this.J=a;this.W=this.J.U();this.videoData=this.J.getVideoData();this.ub=this.J.qb();var c;this.ib=null==(c=this.J.getVideoData(1))?void 0:g.WT(c);this.C={cf:{}};this.G={cf:{}};this.Ha=[];this.va={};this.Wa={};this.Y=!1;this.Vb=g.XT(this.videoData);this.Za=g.CXa(this.videoData,this.J);this.Ob=!!this.videoData.captionTracks.length;this.jc=!!this.videoData.le;this.Xa="3"===this.W.controlsType;this.j=this.N=this.Z=this.Ra=this.tb=null;this.fb=new h5(this.J,this.W);this.B=null;this.Ca=new g.RK(this);
this.K=new g.V({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.ma={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Qv("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Av(d));this.storage=c;var e;this.Nb=!(null==(e=a.kf())||!e.dG());this.D=Wob(this);this.Ia=!this.D&&this.Xa&&this.Nb&&this.Za;g.N(this,this.fb);this.D?this.Na=this.Ma=null:(this.Ma=new g.Ou(this.vS,void 0,this),g.N(this,this.Ma),this.Na=new g.Qu(this.Uba,2E3,this),g.N(this,
this.Na));g.N(this,this.Ca);g.xU(this.player,this.K.element,4);g.N(this,this.K);this.D||this.Ca.T(a,"resize",this.xS);(this.Gb=g.hS(this.W)&&!g.DC()&&!this.J.isFullscreen()&&!this.D&&!this.Ia)&&this.Ca.T(a,"resize",this.p$);this.Ca.T(a,"onPlaybackAudioChange",this.F9);this.Ca.T(a,g.dK("captions"),function(f){b.onCueRangeEnter(f)});
this.Ca.T(a,g.eK("captions"),function(f){b.onCueRangeExit(f)});
this.ib&&this.Ca.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
Xob(this,Pnb()||{});this.player.zc("onCaptionsModuleAvailable")},$ob=function(a){if(1===a.W.Gb||1===a.videoData.iF||"alwayson"===g.DT(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(2===a.W.Gb){if(g.tS(a.W))var c=Yob(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=Inb(a.player.getAudioTrack(),g.tS(a.W));var d=g.DT(a.videoData,"yt:cc");if(void 0===Zob(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===
g.DT(a.videoData,"yt:cc")},j5=function(a,b){if(a.B&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||"FORCED_ON"===a.B},Zob=function(a){var b=void 0,c=g.XC(g.WC(),65);
if(g.tS(a.W)&&null!=c){if(null!=Yob(a))return!1;b=!c}return b},apb=function(a){var b;
a.Vb?b=new $4(a.W,a.videoData,a.getAudioTrack(),a.player):a.Za?b=new E4(a.videoData.j,a.player):a.Ob?b=new g.dW(a.W,a.videoData,a.getAudioTrack()):b=new g.hW(a.W,a.videoData.le,a.videoData.videoId,g.yTa(a.videoData),a.videoData.Om,a.videoData.eventId);return b},l5=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.PT(a.videoData)&&(b=!0);b||(b=a.jc?!1:a.Ob?!1:!0);b=b||bpb(a);b=g.aW(a.j.B,b);var c=null;if(g.tS(a.W)){var d=a.J.isInline()?void 0:g.SC("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.DT(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.KS(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.KS(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.D,
e.length))for(e=g.u(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.DT(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.KS(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||k5(a));d&&c&&g.KS(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=Jnb(d,c));return d}return null},k5=function(a){return a.N&&a.N.j},m5=function(a){var b=k5(a);
return!!b&&a.B===b},cpb=function(a){var b=Inb(a.player.getAudioTrack(),g.tS(a.W)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=l5(a,a.Y):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&j5(a)?c=k5(a):Zob(a)||a.Y||$ob(a)?c=l5(a,a.Y):j5(a)&&(c=k5(a));if(a.D||a.Ia){var d=g.aW(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.If("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.IS(f));h.setAttribute("srclang",g.KS(f));h.setAttribute("id",f.toString());a.Ia||h.setAttribute("src",a.j.Iv(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.kf();c.HC(b);c=
c.Kb();a.Nb&&a.Ca.T(c.textTracks,"change",a.Raa)}else!a.B&&c&&n5(a,c),a.player.zc("onCaptionsTrackListChanged"),a.player.Cm("onApiChange")},dpb=function(a,b){var c=a.J.kf().Kb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},n5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Y=c,a.Y&&(g.tS(a.W)?o5(a,!!b):p5(a,!!b)));a.B=b;j5(a)&&(a.B=k5(a));var d;epb(a,null!=(d=a.B)?d:void 0);a.load()},gpb=function(a,b){if(b instanceof Q4){var c=a.va[b.id];
c&&c.B!==b&&(c.dispose(),delete a.va[b.id],c=null);c||(c=fpb(a,b))&&(a.va[b.id]=c)}else c=b.windowId,a.Wa[c]||(a.Wa[c]=[]),a.Wa[c].push(b)},fpb=function(a,b){var c=hpb(a);
if(!c)return null;var d=a.B?g.KS(a.B):null;d&&g.Qhb.test(d)&&(b.params.Ri=1);var e=a.ub.getPlayerSize();d=e.height*a.ma.height;e=e.width*a.ma.width;"google-live"!==a.W.playerStyle||a.C.isDefault||Object.assign(b.params,a.C);switch(null!=b.params.sA?b.params.sA:1<b.j.length?1:0){case 1:return new a5(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.AL.bind(a),a.J);case 2:return new f5(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.AL.bind(a),a.J);default:return new F4(b,a.C,a.G,c.width,c.height,e,
d,a.W.experiments,a.AL.bind(a),a.J)}},Xob=function(a,b,c){c=void 0===c?!1:c;
var d=q5.cf;a.C={};Object.assign(a.C,q5);a.C.cf={};Object.assign(a.C.cf,d);a.G={cf:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;W4.test(f);e.cf.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;W4.test(f);e.cf.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||q5.windowColor;W4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.cf.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.cf.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.cf;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.cf.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=q5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.cf.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.cf.fontFamily=f;a.loaded&&a.xS();c&&g.RC("yt-player-caption-display-settings",b,2592E3)},jpb=function(a,b,c){b&&!a.Z?(b=Cob({Ri:0,
lang:"en-GB"}),a.Z=[b,new O4(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.yf(a.Z)):!b&&a.Z&&(ipb(a,a.Z),a.Z=null)},ipb=function(a,b){a.player.uo(b);
b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.Ib(a.Ha,c.value);g.Pu(a.Ma)},epb=function(a,b){a.W.L("html5_modify_caption_vss_logging")&&(a.videoData.SB=b)},hpb=function(a){var b=a.ub.getVideoContentRect(!0).height,c=a.ub.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ma.height;c*=a.ma.width;return{width:c,height:b}},p5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},o5=function(a,b){a.J.isInline()||g.RC("yt-player-sticky-caption",b,2592E3)},Yob=function(a){if(!a.J.isInline())return g.SC("yt-player-sticky-caption")},Wob=function(a){var b,c=!(null==(b=a.J.kf())||!b.cG());
return a.Xa&&c&&!a.Za},bpb=function(a){return a.W.L("web_deprecate_always_includes_asr_setting")&&g.tS(a.W)?!0:!!g.XC(g.WC(),66)};
g.RY.prototype.vD=g.fa(45,function(a){var b=2;this.D.has(a)?b=0:g.p3a(this,a)&&(b=1);return b});
g.W_.prototype.vD=g.fa(44,function(a){return this.pd.vD(a)});
g.RY.prototype.mG=g.fa(43,function(a,b,c){this.Na.set(a,{Ds:b,Gy:c})});
g.W_.prototype.mG=g.fa(42,function(a,b,c){this.pd.mG(a,b,c)});
g.cW.prototype.WQ=g.fa(41,function(){return!1});
g.cW.prototype.Ct=g.fa(40,function(){});
g.dW.prototype.Ct=g.fa(39,function(a,b,c){var d=this;this.isDisposed();b=this.Iv(a,b);this.Pr();this.j=g.$B(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.hW.prototype.Ct=g.fa(38,function(a,b,c){var d=this;this.isDisposed();b=this.Iv(a,b);this.Pr();this.j=g.$B(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.GV.prototype.Sy=g.fa(37,function(){for(var a=g.yf(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Rf(a[b])});
g.EY.prototype.Sy=g.fa(36,function(){this.mediaElement.Sy()});
g.GV.prototype.dG=g.fa(35,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.EY.prototype.dG=g.fa(34,function(){return this.mediaElement.dG()});
g.GV.prototype.cG=g.fa(33,function(){return!!this.j.textTracks});
g.EY.prototype.cG=g.fa(32,function(){return this.mediaElement.cG()});
g.GV.prototype.HC=g.fa(31,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.EY.prototype.HC=g.fa(30,function(a){this.mediaElement.HC(a)});
g.Q_.prototype.KD=g.fa(20,function(){return this.Y});
g.b1.prototype.KD=g.fa(19,function(){var a;return(null==(a=g.kU(this))?void 0:a.zz())||null});
g.qU.prototype.zz=g.fa(18,function(){return this.app.KD()});
g.R0.prototype.zz=g.fa(17,function(){var a;return(null==(a=this.Aa)?void 0:a.KD())||null});
g.ZP.prototype.kI=g.fa(3,function(a){return(a=this.qn(a))?a.j:0});
g.ZOa.prototype.kI=g.fa(2,function(){return 0});
var Nnb=/#(.)(.)(.)/,Mnb=/^#(?:[0-9a-f]{3}){1,2}$/i,Unb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
D4.prototype.contains=function(a){a=g.Tb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
D4.prototype.length=function(){return this.segments.length/2};
g.w(Rnb,g.I);g.k=Rnb.prototype;g.k.xa=function(){g.I.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.HA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Vc();var b=this.j;this.j=g.Bb(this.ma.Gq(a).eb);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.D=new D4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.wY=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Xr(a);if(a&&!this.C&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.fC(a);var b=a.eb[0],c;if(null==(c=this.player.getVideoData())?0:c.enableServerStitchedDai)if(c=this.player.zz()){var d=b.j.info.id,e=b.Pa,f=a.eb[0].C;if(this.policy.Ca){if(c=c.mI(f,e,d,3))a.D=c}else if(d=c.rz(f,e,d,3))if(c=c.vD(e),0===c)d&&(a.j=new g.SP(d));else if(2===c){this.N.start();Snb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.En(b.Pa)?(this.D.contains(a.eb[0].Pa)||Tnb(this,a),this.j=g.Bb(a.eb)):Snb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.w(E4,g.cW);g.k=E4.prototype;g.k.Ct=function(a,b,c){var d=this;this.Pr();b=Wnb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?Xnb(this,b,"386"):Xnb(this,b));if(b){var e=1E3*(b.index.kI(b.index.vn())-b.index.getStartTime(b.index.vn())),f=new g.zXa(this.W),h=function(){d.C&&d.C.reset();d.G=!0};
this.W.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new Rnb(f,this.J,b,function(l,m){c(l,a,m,e)},this.K||g.bL(b.info),h)}};
g.k.WQ=function(){var a=this.G;this.G=!1;return a};
g.k.gA=function(a){var b=this.K?[new g.HS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.HS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?Vnb(this,"386"):Vnb(this);b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.bW(this.B,c.value);a()};
g.k.Pr=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Iv=function(){return""};
var W4=/^#(?:[0-9a-f]{3}){1,2}$/i;var aob=["left","right","center","justify"];g.w(F4,g.V);g.k=F4.prototype;g.k.t2=function(a,b){this.Za=a;this.ib=b;var c=g.us(this.element,this.element.parentElement);this.tb=a-c.x;this.ub=b-c.y};
g.k.s2=function(a,b){if(a!==this.Za||b!==this.ib){g.Xu(this.element,"ytp-dragging")||g.Yu(this.element,"ytp-dragging");var c=g.ws(this.element);a=a-this.tb-.02*this.playerWidth;var d=b-this.ub-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.He(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.He(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.He(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.He(c,0,1);this.B.params.Tl=b;this.B.params.Bo=c;this.B.params.nk=
a;this.B.params.isDefault=!1;this.j.Tl=b;this.j.Bo=c;this.j.nk=a;this.j.isDefault=!1;this.va.Tl=b;this.va.Bo=c;this.va.nk=a;this.va.isDefault=!1;this.w_()}};
g.k.q2=function(){g.$u(this.element,"ytp-dragging")};
g.k.w_=function(){this.rB(this.K)};
g.k.getType=function(){return this.type};
g.k.rB=function(a){var b=this.Gb?0:Math.min(this.NW(),this.maxWidth),c=this.MW(),d=this.Gb;if(d){var e=getComputedStyle(this.D.parentNode);e=G4(e.borderLeftWidth)+G4(e.borderRightWidth)+G4(e.paddingLeft)+G4(e.paddingRight)}else e=0;var f=e;e="";3===this.B.params.Ri&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.ks(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.AM(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=.96*this.j.nk+2;h=this.j.Tl;switch(h){case 0:case 3:case 6:(d=this.j.cf.fontSizeIncrement)&&0<d&&2!==this.j.Ri&&3!==this.j.Ri&&(l=Math.max(l/(1+2*d),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=.96*this.j.Bo+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.ks(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],"string"===typeof e.text&&(d+=e.text.split("\n").length-1,e.append||0===b||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.AM=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ha||this.K.length>b)b=0,this.Ha=!1,this.K=[],this.N=this.Na=this.Ma=null,g.Pf(this.D);for(;b<a.length;b++)fob(this,a[b])};
g.k.NW=function(){return 0};
g.k.MW=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};hob.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
hob.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var iob=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];H4.prototype.set=function(a){this.type=a};
H4.prototype.get=function(){return this.type};
I4.prototype.clear=function(){this.state=0};
I4.prototype.update=function(){this.state=2===this.state?1:0};
I4.prototype.Ke=function(){return 0!==this.state};
I4.prototype.matches=function(a,b){return this.Ke()&&a===this.Uu&&b===this.qs};
nob.prototype.reset=function(){this.timestamp=this.j=0};
J4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
J4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
J4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var oob=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],pob=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],qob=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],rob=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];vob.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
gob.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};zob.prototype.D=function(){};g.w(O4,g.cK);O4.prototype.toString=function(){return g.cK.prototype.toString.call(this)};g.w(P4,g.I);P4.prototype.Wn=function(){return[]};
P4.prototype.reset=function(){};g.w(Q4,g.cK);Q4.prototype.toString=function(){return g.cK.prototype.toString.call(this)};
var R4=0;g.w(S4,P4);S4.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
S4.prototype.Wn=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.u(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.u(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=U4(a,"b");
null!=l&&(h.bold=l);l=U4(a,"i");null!=l&&(h.italic=l);l=U4(a,"u");null!=l&&(h.underline=l);l=V4(a,"et");null!=l&&(h.charEdgeStyle=l);l=V4(a,"of");null!=l&&(h.offset=l);l=X4(a,"bc");null!=l&&(h.background=l);l=X4(a,"ec");null!=l&&(h.UM=l);l=X4(a,"fc");null!=l&&(h.color=l);l=V4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=T4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=T4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=T4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=V4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.pg=10<l?l-1:l);a=V4(a,"hg");null!=a&&(h.KX=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Dob(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Eob(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.u(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=Fob(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!U4(m,"a");l=(T4(m,"t")||0)+l;var n=T4(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=null!=m.getAttribute("d"));for(m=0;m<r.length;m++){var t=r[m],v=void 0;0<m&&(h=!0);var x=void 0;1===t.nodeType&&(x=t);if(x&&"s"===x.tagName){if((t=(t=x.getAttribute("p"))?this.pens[t]:null)&&t.pg&&(1===t.pg?(t=r.slice(m,
m+4),4===t.length&&(v=Bob(l,n,f,h,p,t,this.pens),m+=3)):v=Bob(l,n,f,h,p,[x],this.pens)),!v){var A=x;v=l;x=n;t=f;var E=h,F=p,G=A.textContent?A.textContent:"",M=A.getAttribute("p");M=M?this.pens[M]:null;A=T4(A,"t")||0;v=new O4(v+A,x-A,F,t,G,E,M)}}else v=new O4(l,n,p,f,t.textContent||"",h,q);c.push(v);this.B=v}if(0<c.length)for(c[0].windowId===this.D&&(this.j=Fob(this,a,b,!0),d.push(this.j)),a=g.u(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var kpb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(Y4,P4);Y4.prototype.reset=function(){this.B.clear()};
Y4.prototype.Wn=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.u(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.UM=Z4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=Z4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=Z4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.pg=10<h?h-1:h,f.Ao=kpb.get(f.pg));e.hgHorizGroup&&(f.KX=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.u(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),void 0!==e.mhModeHint&&(f.sA=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Ri=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.hS=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=Z4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.u(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.nk=e.ahHorPos),void 0!==e.apPoint&&(f.Tl=e.apPoint),void 0!==e.avVerPos&&(f.Bo=e.avVerPos),void 0!==e.ccCols&&(f.ys=e.ccCols),void 0!==e.rcRows&&(f.zr=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.u(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Gob(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+R4++,d=Gob(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;0===f&&(f=5E3);l=this.B.get(h);
var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],v=t.utf8;if(v){var x=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if(2===(null!=l.params.sA?l.params.sA:1<l.j.length?1:0)&&n&&"\n"===v)continue;t=null;var E=[],F;if(F=A&&1===A.pg){F=q;var G=m;if(G+3>=F.length||!F[G+1].pPenId||!F[G+2].pPenId||!F[G+3].pPenId)F=!1;else{var M=F[G+1].pPenId;(M=this.j.get(M))&&M.pg&&2===M.pg?(M=F[G+2].pPenId,M=this.j.get(M),!M||!M.pg||3>M.pg?F=!1:
(M=F[G+3].pPenId,F=(M=this.j.get(M))&&M.pg&&2===M.pg?!0:!1)):F=!1}}if(F)x=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,G=this.j.get(q[m+2].pPenId),v=Aob(v,x,F,t,G),t=new O4(e,f,p,h,v,n,A),m+=3;else{if(-1<v.indexOf("<")){var P=void 0;E=A;F=r;G=e;M=f;var R=x,ba=p,na=n,ta=[],ka=g.w2("<html>"+v+"</html>");if(!ka.getElementsByTagName("parsererror").length&&(null==(P=ka.firstChild)?0:P.childNodes.length))for(P=g.u(ka.firstChild.childNodes),ka=P.next();!ka.done;ka=P.next()){ka=ka.value;var va=void 0,ea=void 0,
Y=null!=(ea=null==(va=ka.textContent)?void 0:va.replace(/\n/g,""))?ea:"";if(3!==ka.nodeType||Y&&null==Y.match(/^ *$/)){va={};Object.assign(va,E||F);ea=void 0;switch(null==(ea=ka)?void 0:ea.tagName){case "b":va.bold=!0;break;case "i":va.italic=!0;break;case "u":va.underline=!0}ta.push(new O4(G+R,M-R,ba,l.id,Y,na,va))}}E=ta}E.length||(E=[new O4(e+x,f-x,p,l.id,v,n,A||r)])}if(E.length)for(n=g.u(E),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=
[];return b};g.w($4,g.cW);$4.prototype.Ct=function(a,b,c){Lnb(this.videoData.videoId,a.vssId,c)};
$4.prototype.gA=function(a){if(this.audioTrack)for(var b=g.u(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.bW(this.B,c.value);a()};g.w(a5,F4);a5.prototype.AM=function(a){var b=this.B.j;F4.prototype.AM.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,lpb);var e=c.j;var f=d}fob(this,c,d)}};
var lpb={d8:!0};g.w(b5,zob);b5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+R4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new Q4(c,d-c,5,f,{textAlign:0,Tl:0,nk:2.5*b,Bo:5.33*a});e=new O4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.w(e5,P4);e5.prototype.Wn=function(a){a=new b5(a,a.byteLength,this.B);if(Hob(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.C=d5(a)*(1E3/45):1===a.version&&(a.C=4294967296*d5(a)+d5(a)),a.G=c5(a);0<a.G;a.G--){var b=c5(a),c=c5(a),d=c5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.C,type:this.track,HV:c,IV:d,order:b.j.length}))}mob(this.j,a);return a.B}return[]};
e5.prototype.reset=function(){this.j.clear()};g.w(f5,F4);g.k=f5.prototype;g.k.w_=function(){g.Su(this.Xa)};
g.k.haa=function(){g.$u(this.element,"ytp-rollup-mode");this.rB(this.jc,!0)};
g.k.MW=function(){return this.C?this.ma:this.Y};
g.k.NW=function(){return this.C?this.Y:this.ma};
g.k.rB=function(a,b){this.jc=a;if(this.B.params.zr){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Ob=this.ma;this.Y=this.ma=0;F4.prototype.rB.call(this,a);Lob(this,b)}F4.prototype.rB.call(this,a)};g.w(g5,P4);
g5.prototype.Wn=function(a,b){var c=[];a=a.split(mpb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!npb.test(e)){var h=opb.exec(e);if(h&&4<=h.length){var l=Nob(h[1]),m=Nob(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.u(n);for(var v=n.next();!v.done;v=n.next())if(v=v.value.split(":"),2===v.length){var x=v[1];switch(v[0]){case "line":v=x.split(",");v[0].endsWith("%")&&(p=v[0],h.Bo=Number.parseInt(p,10),2===v.length&&(q=v[1].trim()));break;case "position":v=
x.split(",");r=v[0];h.nk=Number.parseInt(r,10);2===v.length&&(t=v[1].trim());break;case "align":switch(x){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.nk=0;break;case 1:h.nk=100;break;case 2:h.nk=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Tl=q}e=e.substring(opb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=Oob(l,m,5,t),m=new O4(l,m,5,f.id,h,!1,g.md(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(ppb),1===q.length?(h=5,t=Oob(l,m,h,t)):(p=h=6,t=Object.assign({ys:32},t),t=new Q4(l,m,p,"_"+R4++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(v=g.w2("<html>"+n+"</html>"),v.getElementsByTagName("parsererror").length?
(x=v.createElement("span"),x.appendChild(v.createTextNode(n))):x=v.firstChild,Mob(this,p,m-(p-l),h,t,0<r,x,e,c)):p=Nob(n)+f}opb.lastIndex=0}}return c};
var npb=/^NOTE/,mpb=/(?:\r\n|\r|\n){2,}/,opb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ppb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.FY.FI(g5,{Wn:"wvppt"});g.w(h5,g.I);
h5.prototype.Wn=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a){var e=d,f=Rob(this,a,c),h=[];try{for(var l=g.u(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.bS;h="string"!==typeof p?h.concat(Sob(this,b,p,q,e)):"WEBVTT"===p.substring(0,6)?h.concat(Tob(this,p,q)):h.concat(Vob(this,b,p,q))}var r=h}catch(t){g.CF(t),this.clear(),r=[]}if(0!==r.length)return r}a=Pob(a);if(!a)return[];try{return"string"!==typeof a?Sob(this,b,a,c,d):"WEBVTT"===a.substring(0,6)?Tob(this,a,c):Vob(this,b,a,
c)}catch(t){return g.CF(t),this.clear(),[]}};
h5.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
h5.prototype.reset=function(){this.j&&this.j.reset()};
h5.prototype.xa=function(){g.I.prototype.xa.call(this);this.clear()};var q5={windowColor:"#080808",windowOpacity:0,textAlign:2,Tl:7,nk:50,Bo:100,isDefault:!0,cf:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(i5,g.$V);g.k=i5.prototype;g.k.xa=function(){if(this.D||this.Ia){var a=this.J.kf();a&&!a.isDisposed()&&a.Sy()}else jpb(this,!1);g.$V.prototype.xa.call(this)};
g.k.TR=function(){return this.W.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Za};
g.k.Wt=function(){if(this.Xa)return this.D||this.Ia;var a=this.getAudioTrack();if(this.TR()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Inb(a,g.tS(this.W));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?j5(this):Zob(this)||j5(this)?!0:$ob(this)};
g.k.load=function(){var a=this;g.$V.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.fb.clear(),this.D?dpb(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Ct(this.B,"json3",function(b,c,d,e){if(b){var f;epb(a,null!=(f=a.B)?f:void 0);a.j.WQ()&&(a.Ha=[],a.J.Cf("captions"),g.Pu(a.Ma),a.fb.reset());if(a.videoData.Bj){var h;d=(null!=(h=d)?h:0)+a.videoData.Bj}b=a.fb.Wn(b,c,d,e);if(a.ib)for(c=g.u(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.Zk=a.videoData.Bj;c=!a.W.L("html5_keep_caption_data_after_seek")&&a.Za;a.player.yf(b,void 0,c);!a.Y||a.Ia||m5(a)||!a.W.Om||g.HJ(a.W)||g.jS(a.W)||g.iH(a.W)||"shortspage"===a.W.Ma||a.player.isInline()||(g.Tu(a.Na),b=Cob({Tl:0,nk:5,Bo:5,zr:2,textAlign:0,Ri:0,lang:"en-GB"}),a.Ra=[b],c=["Click "," for settings"],a.tb||(e=new g.$F(g.Gwa()),g.N(a,e),a.tb=e.element),e=b.end-b.start,(f=g.IS(a.B))&&a.Ra.push(new O4(b.start,e,0,b.id,f)),a.Ra.push(new O4(b.start,e,0,b.id,c[0]),new O4(b.start,e,0,b.id,a.tb,
!0),new O4(b.start,e,0,b.id,c[1],!0)),a.player.yf(a.Ra),g.Ru(a.Na));!a.Y||a.Ia||m5(a)||(g.tS(a.W)?o5(a,!0):p5(a,!0),a.N&&(a.N.D=a.B),a.player.Go());a.Y=!1}}),this.D||this.Ia||m5(this)||this.player.zc("captionschanged",g.JS(this.B))):(this.j=apb(this),g.N(this,this.j),this.j.gA(function(){cpb(a)}))};
g.k.unload=function(){this.D&&this.B?dpb(this,!1):(this.Na&&g.Tu(this.Na),this.player.Cf("captions"),this.Ha=[],this.j&&this.j.Pr(),this.fb.clear(),this.Z&&this.player.yf(this.Z),this.xS());g.$V.prototype.unload.call(this);this.player.Go();this.player.zc("captionschanged",{})};
g.k.create=function(){this.Wt()&&this.load();var a;a:{var b,c,d;if(this.W.L("suggest_caption_correction_menu_item")&&this.W.L("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.u(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.J.ra("showpromotooltip",this.K.element)};
g.k.Raa=function(){for(var a=this.J.kf().Kb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.aW(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&n5(this,b,!0)};
g.k.pda=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ha.push(a);g.Pu(this.Ma)};
g.k.onCueRangeExit=function(a){g.Ib(this.Ha,a);this.j instanceof E4&&this.j.K&&this.player.uo([a]);g.Pu(this.Ma)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.Uba=function(){ipb(this,this.Ra);this.Ra=null};
g.k.vS=function(){var a=this;if(!this.Gb||!this.D){this.Ma.stop();g.dba(this.Wa);this.Ha.sort(g.RAa);var b=this.Ha;if(this.Z){var c=g.ot(b,function(f){return-1===this.Z.indexOf(f)},this);
c.length&&(b=c)}b=g.u(b);for(c=b.next();!c.done;c=b.next())gpb(this,c.value);b=g.u(Object.entries(this.va));var d=b.next();for(c={};!d.done;c={Mz:void 0,gp:void 0},d=b.next()){var e=g.u(d.value);d=e.next().value;e=e.next().value;c.Mz=d;c.gp=e;this.Wa[c.Mz]?(c.gp.element.parentNode||(c.gp instanceof f5||c.gp instanceof a5||g.ed(this.va,function(f){return function(h,l){l!==f.Mz&&h.B.params.Tl===f.gp.B.params.Tl&&h.B.params.nk===f.gp.B.params.nk&&h.B.params.Bo===f.gp.B.params.Bo&&(h.dispose(),delete a.va[l]);
return l===f.Mz}}(c),this),this.K.element.appendChild(c.gp.element)),c.gp.rB(this.Wa[c.Mz])):(c.gp.dispose(),delete this.va[c.Mz])}}};
g.k.Zba=function(){Xob(this,{},!0);this.player.zc("captionssettingschanged")};
g.k.l7=function(){var a=q5.cf;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:q5.windowColor,windowOpacity:q5.windowOpacity};var b=Pnb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.U0=function(a,b){var c={};Object.assign(c,Pnb());Object.assign(c,a);Xob(this,c,b);this.player.zc("captionssettingschanged")};
g.k.xS=function(){!this.D&&this.loaded&&(g.bd(this.va,function(a,b){a.dispose();delete this.va[b]},this),this.vS())};
g.k.Lh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.He(b,-2,4);this.U0({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&n5(this,this.B,!0);break;case "stickyLoading":void 0!==b&&this.W.K&&(g.tS(this.W)?o5(this,!!b):p5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.bb(b))break;if(g.md(b)){n5(this,null,!0);break}a=g.aW(this.j.B,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?Jnb(e,b.translationLanguage):e)}this.aL(b.position);!c||c===this.B&&this.loaded||(b=g.SMa(),a=g.KS(c),b.length&&a===b[b.length-1]||(b.push(a),g.RC("yt-player-caption-language-preferences",b)),g.tS(this.W)&&!this.J.isInline()&&g.RC("yt-player-caption-sticky-language",a,2592E3),n5(this,c,!0))}else return this.loaded&&this.B&&!m5(this)?g.JS(this.B):{};return"";case "tracklist":return this.j?g.Er(g.aW(this.j.B,!(!b||!b.includeAsr)),function(f){return g.JS(f)}):
[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||void 0===b||jpb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||jpb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.SMa();case "defaultTranslationSourceTrackIndices":return this.j?this.j.N:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.K&&a.push("stickyLoading");return a};
g.k.Iq=function(){var a=this.B;if(this.W.L("html5_modify_caption_vss_logging")){var b;return(a=null!=(b=this.videoData.SB)?b:null)?{cc:g.vRa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.KS(a)),{cc:b}):{}};
g.k.bda=function(){this.isSubtitlesOn()?(g.tS(this.W)?o5(this,!1):p5(this,!1),epb(this),this.unload(),j5(this,!0)&&n5(this,k5(this),!1)):this.z0()};
g.k.z0=function(){this.isSubtitlesOn()||n5(this,m5(this)||!this.B?l5(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!m5(this)};
g.k.F9=function(){var a=m5(this);j5(this,a)?n5(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.TR()&&(this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Wt()&&(a?n5(this,l5(this),!1):this.load()))};
g.k.aL=function(a){a&&(this.ma={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.ma.top+"%",this.K.element.style.left=100*this.ma.left+"%",this.K.element.style.width=100*this.ma.width+"%",this.K.element.style.height=100*this.ma.height+"%",this.K.element.style.position="absolute",a=hpb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){"newdata"===a&&(this.videoData=b,this.loaded&&this.unload(),this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.zc("captionschanged",{})),this.Wt()&&this.load())};
g.k.getAudioTrack=function(){return this.ib&&2===this.player.getPresentingPlayerType()?this.videoData.yl:this.player.getAudioTrack()};
g.k.p$=function(){var a=this.J.kf();a&&!a.isDisposed()&&a.Sy();this.J.isFullscreen()?(this.D=this.Xa=!0,this.loaded&&cpb(this)):(this.Xa="3"===this.W.controlsType,this.D=Wob(this));n5(this,this.B)};
g.k.AL=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.ob("innertubeCommand",d)};
g.FY.FI(i5,{vS:"smucd"});g.ZV("captions",i5);})(_yt_player);
