(function(g){var window=this;'use strict';var Mrb=function(a,b){a.ob("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.bv(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.hh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.RS&&(b.lengthText?(e=b.lengthText||null,f=b.lw||null):b.lengthSeconds&&(e=g.bH(b.lengthSeconds),f=g.bH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.KRa(d).type;var l=b instanceof g.RS?b.isLivePlayback:null,m=b instanceof g.RS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.jK("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Sk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.ls};b instanceof g.QS&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.U(),c=b.D;
g.V.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",La:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],ya:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",
La:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",ya:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",La:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ya:"{{title}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ya:"{{author}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ya:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.V({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",ya:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],
ya:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",La:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",ya:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",ya:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",ya:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",ya:"{{author_and_views}}"}]}]}]});
g.N(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Fa("ytp-autonav-endscreen-link-container"),"click",this.cT);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({I:"div",S:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.V({I:"div",S:"ytp-autonav-endscreen-button-container"});g.N(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.V({I:"button",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel auto-play"},ya:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.Ta("click",this.A2,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.V({I:"a",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},ya:"Play now"});g.N(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.Ta("click",this.cT,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Nrb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Qu(function(){Orb(c)},
500);
g.N(this,this.D);this.bT();this.T(a,"autonavvisibility",this.bT);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.z2),this.T(a,"onAutonavCoundownStarted",this.G9))},o6=function(a){var b=a.J.zn(!0,a.J.isFullscreen());
g.bv(a.container.element,"ytp-autonav-endscreen-small-mode",a.Vg(b));g.bv(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.JK);g.bv(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Mf());g.bv(a.J.getRootNode(),"countdown-running",a.Wk());g.bv(a.container.element,"ytp-player-content",a.J.Mf());g.ks(a.overlay.element,{width:b.width+"px"});if(!a.Wk()){a.J.Mf()?Prb(a,Math.round(Qrb(a)/1E3)):Prb(a);b=!!a.suggestion&&!!a.suggestion.ls;var c=a.J.Mf()||!b;
g.bv(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.bv(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.cG(a.B,a.J.Mf());g.bv(a.element,"ytp-enable-w2w-color-transitions",Rrb(a))}},Orb=function(a){var b=Qrb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Prb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Wk()?a.select(!0):a.Wk()&&a.D.start()},Qrb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.OB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Ms()?a.J.Ms():g.uJ(a.J.U().experiments,"autoplay_time")||1E4},Nrb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.q6;a.K=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Rrb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},Prb=function(a,b){b=void 0===b?-1:b;
a=a.j.Fa("ytp-autonav-endscreen-upnext-header");g.Pf(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Nf("Up next in $SECONDS".slice(0,d)));var e=g.If("span");g.Wu(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Vf(e,b);a.appendChild(e);a.appendChild(g.Nf("Up next in $SECONDS".slice(d+c.length)));return}}g.Vf(a,"Up next")},p6=function(a,b){g.V.call(this,{I:"div",
La:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.V.call(this,{I:"div",
La:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",ya:"Up Next"},{I:"span",S:"ytp-upnext-title",ya:"{{title}}"},{I:"span",S:"ytp-upnext-author",ya:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
ya:"Auto-play is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Fa("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Qu(this.lH,5E3,this);this.B=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.V({I:"button",La:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel auto-play"},ya:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.Ta("click",this.B2,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.N(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.C2);this.api.createClientVe(b,this,115130);this.dT();this.T(a,"autonavvisibility",this.dT);this.T(a,"mdxnowautoplaying",this.r$);this.T(a,"mdxautoplaycanceled",this.s$);g.bv(this.element,"ytp-upnext-mobile",this.api.U().B)},Srb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.OB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Ms()?a.api.Ms():g.uJ(a.api.U().experiments,"autoplay_time")||1E4},Trb=function(a,b){b=Srb(a,b);
var c=Math,d=c.min;var e=(0,g.yD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Wk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Wk()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",La:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ya:"More videos"}]});this.N=new g.V({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new n6(this.player);g.N(this,this.B);this.B.Ja(this.element);a.getVideoData().Wf?this.j=this.B:(this.j=new q6(a),g.xU(this.player,this.j.element,4),g.N(this,this.j));this.overlay=new g.V({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.RK(this);g.N(this,this.D);g.N(this,this.table);this.table.Ja(this.element);this.table.show();g.N(this,this.N);this.N.Ja(this.table.element);this.hide()},s6=function(a){var b=a.Mf();
b!==a.G&&(a.G=b,a.player.ra("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},t6=function(a,b){g.V.call(this,{I:"button",
La:["ytp-watch-on-youtube-button","ytp-button"],ya:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.Q_();2===this.buttonType&&g.Yu(this.element,"ytp-continue-watching-button");this.Ta("click",this.onClick);this.Ta("videodatachange",this.Q_);g.cG(this,!0)},u6=function(a,b){p6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Ze=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new t6(a,2);g.N(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},Urb=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.V({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",ya:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.N(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.HW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Fl,b.subscribed,"trailer-endscreen",null,a,!1);g.N(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Sa);this.Sa();this.hide()},v6=function(a){var b=a.U(),c=g.PK||g.cS?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.V.call(this,{I:"a",La:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",ya:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",ya:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",ya:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",ya:"{{duration}}"}]}]}]},{I:"span",La:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",ya:"{{playlist_length}}"},")"]}]},{I:"span",La:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",ya:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.RK(this);g.N(this,this.j);this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},w6=function(a){p6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.RK(this);g.N(this,this.B);this.K=new g.Qu(function(){g.Yu(b.element,"ytp-show-tiles")},0);
g.N(this,this.K);var c=new g.V({I:"button",La:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},V:[g.oG()]});g.N(this,c);c.Ja(this.element);c.Ta("click",this.G2,this);this.table=new g.$F({I:"div",S:"ytp-endscreen-content"});g.N(this,this.table);this.table.Ja(this.element);c=new g.V({I:"button",La:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},V:[g.pG()]});g.N(this,c);c.Ja(this.element);c.Ta("click",this.F2,this);a.getVideoData().Wf?this.j=new n6(a,!0):this.j=new q6(a);
g.N(this,this.j);g.xU(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},x6=function(a){return g.yU(a.player)&&a.KC()&&!a.D},y6=function(a){var b=a.Mf();
b!==a.N&&(a.N=b,a.player.ra("autonavvisibility"))},z6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t6(a,1);g.N(this,this.watchButton);this.watchButton.Ja(this.element);g.hgb(a)&&(this.j=new g.y2(a),g.N(this,this.j),this.B=new g.V({I:"div",La:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.N(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},Yrb=function(a){g.$V.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.RK(this);g.N(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.zC(g.lS(c))&&d&&!g.uU(a)?(this.B=!0,this.endScreen=new u6(a,g.lU(a))):a.kd()?this.endScreen=new z6(a):Vrb(a)?(this.D=!0,Wrb(this),this.j?this.endScreen=new r6(a):this.endScreen=new w6(a)):c.Yg?this.endScreen=new Urb(a):this.endScreen=new p6(a);g.N(this,this.endScreen);g.xU(a,this.endScreen.element,4);Xrb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.dK("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.eK("endscreen"),function(e){b.onCueRangeExit(e)})},Wrb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Jl&&a.C===b.Wf)return!1;a.j=b.Jl;a.C=b.Wf;return!0},Vrb=function(a){a=a.U();
return a.le&&!a.Yg},Xrb=function(a){a.player.Cf("endscreen");
var b=a.player.getVideoData();b=new g.cK(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.cK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.yf([b,c])};
g.qU.prototype.Ms=g.fa(16,function(){return this.app.Ms()});
g.b1.prototype.Ms=g.fa(15,function(){return this.getVideoData().UU});
g.mU.prototype.Dr=g.fa(14,function(a){this.Di().Dr(a)});
g.hX.prototype.Dr=g.fa(13,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.oY.prototype.Dr=g.fa(12,function(a){this.overflowButton&&this.overflowButton.Dr(a)});
g.mU.prototype.Er=g.fa(11,function(a){this.Di().Er(a)});
g.mX.prototype.Er=g.fa(10,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.oY.prototype.Er=g.fa(9,function(a){this.shareButton&&this.shareButton.Er(a)});
g.mU.prototype.nB=g.fa(8,function(a){this.Di().nB(a)});
g.AW.prototype.nB=g.fa(7,function(a){this.LQ!==a&&(this.LQ=a,this.cq())});
g.mU.prototype.mB=g.fa(6,function(a){this.Di().mB(a)});
g.oY.prototype.mB=g.fa(5,function(a){this.KQ!==a&&(this.KQ=a,this.bq())});g.w(m6,g.V);m6.prototype.select=function(){this.J.Jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.fD||void 0)&&this.J.logClick(this.element)};
m6.prototype.onClick=function(a){g.iV(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.w(n6,g.V);g.k=n6.prototype;g.k.yG=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.updateValue("url",this.suggestion.Sk()),o6(this))};
g.k.Wk=function(){return 0<this.C};
g.k.vB=function(){this.Wk()||(this.C=Date.now(),Orb(this),Mrb(this.J,Qrb(this)),g.bv(this.J.getRootNode(),"countdown-running",this.Wk()))};
g.k.Vw=function(){this.Xp();Orb(this);var a=this.j.Fa("ytp-autonav-endscreen-upnext-header");a&&g.Vf(a,"Up next")};
g.k.Xp=function(){this.Wk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Xp()};
g.k.cT=function(a){g.iV(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Fa("ytp-autonav-endscreen-link-container")&&(a=this.j.Fa("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.ob("innertubeCommand",this.K),this.Xp()):this.select())};
g.k.A2=function(){this.J.logClick(this.cancelButton.element);g.sU(this.J,!0);this.G&&this.J.ob("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Nrb(this,b);var c;this.G=null==(c=b.i6)?void 0:c.command};
g.k.G9=function(a){if(Rrb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.jH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.jH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.jH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.jH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.jH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.jH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.bv(this.element,"ytp-w2w-animate",!0)}};
g.k.z2=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.bv(this.element,"ytp-w2w-animate",!1)};
g.k.bT=function(){var a=this.J.Mf();this.N&&this.Jb!==a&&g.cG(this,a);o6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Fa("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Vg=function(a){return 400>a.width||459>a.height};g.w(p6,g.V);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.KC=function(){return!1};
g.k.Mf=function(){return!1};
g.k.fY=function(){return!1};g.w(q6,g.V);g.k=q6.prototype;g.k.lH=function(){this.notification&&(this.D.stop(),this.Tc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.yG=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.dT=function(){g.cG(this,this.api.Mf());this.api.logVisibility(this.element,this.api.Mf());this.api.logVisibility(this.Fa("ytp-upnext-autoplay-icon"),this.api.Mf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Mf())};
g.k.A$=function(){window.focus();this.lH()};
g.k.vB=function(a){var b=this;this.Wk()||(g.IE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.yD)(),this.j=new g.Qu(function(){Trb(b,a)},25),Trb(this,a),Mrb(this.api,Srb(this,a)));
g.$u(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Wk=function(){return!!this.j};
g.k.Vw=function(){this.Xp();this.B=(0,g.yD)();Trb(this);g.Yu(this.element,"ytp-upnext-autoplay-paused")};
g.k.Xp=function(){this.Wk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.lH(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.hh()}),this.C=this.T(this.notification,"click",this.A$),this.D.start())}this.Xp();this.api.nextVideo(!1,a)};
g.k.C2=function(a){!g.Uf(this.cancelButton.element,a.target)&&g.iV(a,this.api)&&(this.api.Mf()&&this.api.logClick(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.B2=function(){this.api.Mf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.sU(this.api,!0)};
g.k.r$=function(a){this.api.getPresentingPlayerType();this.show();this.vB(a)};
g.k.s$=function(){this.api.getPresentingPlayerType();this.Xp();this.hide()};
g.k.xa=function(){this.Xp();this.lH();g.V.prototype.xa.call(this)};g.w(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.D.T(this.player,"appresize",this.WB);this.D.T(this.player,"onVideoAreaChange",this.WB);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.eT);this.D.T(this.player,"onAutonavCancelled",this.D2);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.sU(this.player,!1);g.yU(this.player)&&this.KC()&&!this.C?(s6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.vB():3===this.videoData.autonavState&&this.j.Vw()):(g.sU(this.player,!0),s6(this));this.WB()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.Vw();s6(this)};
g.k.WB=function(){var a=this.player.zn(!0,this.player.isFullscreen());s6(this);o6(this.B);g.bv(this.element,"ytp-autonav-cancelled-small-mode",this.Vg(a));g.bv(this.element,"ytp-autonav-cancelled-tiny-mode",this.LI(a));g.bv(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.ks(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.bv(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.rT(this.videoData);b&&(this.j.yG(b),this.j!==this.B&&this.B.yG(b))}if(a&&a.length)for(b=0;b<Zrb.length;++b){var c=Zrb[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.N(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.WB()}};
g.k.eT=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Xp(),this.Jb&&this.WB()):(this.K=!0,this.Mf()&&(2===a?this.j.vB():3===a&&this.j.Vw()))};
g.k.D2=function(a){a?this.eT(1):(this.C=null,this.K=!1)};
g.k.KC=function(){return 1!==this.videoData.autonavState};
g.k.Vg=function(a){return(910>a.width||459>a.height)&&!this.LI(a)&&!(400>=a.width||360>=a.height)};
g.k.LI=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Mf=function(){return this.Jb&&g.yU(this.player)&&this.KC()&&!this.C};
var Zrb=[1,3,2,4];g.w(t6,g.V);g.k=t6.prototype;g.k.Q_=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.jV(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.dS(b)){var c={};g.dS(b)&&g.fU(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.yP(c,b);a=g.an(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Jb&&this.Z)};
g.k.show=function(){g.V.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.V.prototype.hide.call(this);this.logVisibility()};
g.k.Nc=function(a){g.V.prototype.Nc.call(this,a);this.logVisibility()};g.w(u6,p6);u6.prototype.show=function(){3!==this.player.getPlayerState()&&(p6.prototype.show.call(this),this.Ze.mB(!0),this.Ze.Er(!0),this.J.U().Ee||this.Ze.Dr(!0),this.J.logVisibility(this.element,!0),this.watchButton.Nc(!0))};
u6.prototype.hide=function(){p6.prototype.hide.call(this);this.Ze.mB(!1);this.Ze.Er(!1);this.Ze.Dr(!1);this.J.logVisibility(this.element,!1);this.watchButton.Nc(!1)};g.w(Urb,p6);Urb.prototype.Sa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Fl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.w(v6,g.V);v6.prototype.select=function(){this.api.Jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.fD||void 0)&&this.api.logClick(this.element)};
v6.prototype.onClick=function(a){if(g.dS(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Sk(),c={};g.dUa(this.api,c,"emb_rel_end");b=g.an(b,c);g.jV(b,this.api,a)}else g.iV(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
v6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
v6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Of?!1:b.D};g.w(w6,p6);g.k=w6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.hq();this.B.T(this.player,"appresize",this.hq);this.B.T(this.player,"onVideoAreaChange",this.hq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.CL);this.B.T(this.player,"onAutonavCancelled",this.E2);a=this.videoData.autonavState;a!==this.Y&&this.CL(a);this.B.T(this.element,"transitionend",this.Saa)};
g.k.destroy=function(){g.OC(this.B);g.xb(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.$u(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.KC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Jb;p6.prototype.show.call(this);g.$u(this.element,"ytp-show-tiles");this.player.U().B?g.Su(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.sU(this.player,!1);x6(this)?(y6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.vB():3===this.videoData.autonavState&&this.j.Vw()):(g.sU(this.player,!0),y6(this));a!==this.Jb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Jb;p6.prototype.hide.call(this);this.j.Vw();y6(this);a!==this.Jb&&this.player.logVisibility(this.element,!1)};
g.k.Saa=function(a){a.target===this.element&&this.hq()};
g.k.hq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.rT(d)];if(e.length){g.Yu(this.element,"ytp-endscreen-paginate");var f=this.J.zn(!0,this.J.isFullscreen());if(a=g.lU(this.J))a=a.Ch()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,v=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&v)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(v)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.vs(f,n,p);g.ks(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.yG(g.rT(this.videoData));this.j instanceof
n6&&o6(this.j);g.bv(this.element,"ytp-endscreen-takeover",x6(this));y6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.Ie(q+this.C,c),0!==t){r=this.stills[h];r||(r=new v6(this.player),this.stills[h]=r,f.appendChild(r.element));v=Math.floor(p*m/b);var x=Math.floor(n*l/a),A=Math.floor(p*(m+t)/b)-v-4,E=Math.floor(n*(l+t)/a)-x-4;g.qs(r.element,x,v);g.vs(r.element,E,A);g.ks(r.element,"transitionDelay",
(m+l)/20+"s");g.bv(r.element,"ytp-videowall-still-mini",1===t);g.bv(r.element,"ytp-videowall-still-large",2<t);t=Math.max(E,A);g.bv(r.element,"ytp-videowall-still-round-large",256<=t);g.bv(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.bv(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),v=g.Xu(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(r,q,v),g.dS(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Sk(),v={},g.fU(r.api,"addEmbedsConversionTrackingParams",[v]),t=g.an(t,g.yP(v,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.bv(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Rf(a.element),g.vb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.hq())};
g.k.F2=function(){this.C+=this.stills.length;this.hq()};
g.k.G2=function(){this.C-=this.stills.length;this.hq()};
g.k.fY=function(){return this.j.Wk()};
g.k.CL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Xp(),this.Jb&&this.hq()):(this.G=!0,this.Jb&&x6(this)&&(2===a?this.j.vB():3===a&&this.j.Vw()))};
g.k.E2=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.CL(1)}else this.D=null,this.G=!1;this.hq()};
g.k.Mf=function(){return this.Jb&&x6(this)};g.w(z6,p6);z6.prototype.TD=function(){var a;return null==(a=this.j)?void 0:a.TD()};
z6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.TD();g.bv(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.lU(this.player))||c.nB(!0);this.player.logVisibility(this.element,!0);this.watchButton.Nc(!0)}};
z6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.lU(this.player))||a.nB(!1);this.player.logVisibility(this.element,!1);this.watchButton.Nc(!1)};g.w(Yrb,g.$V);g.k=Yrb.prototype;g.k.Wt=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.kd()||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.rT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Vrb(this.player)||d;a=a.wk;c=this.player.sD();return d&&!a&&!c&&!b};
g.k.Mf=function(){return this.endScreen.Mf()};
g.k.q8=function(){return this.Mf()?this.endScreen.fY():!1};
g.k.xa=function(){this.player.Cf("endscreen");g.$V.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Bb().Me.get("heartbeat"),d=g.rT(a);!d||b.videoId!==d.videoId||a.OS?(this.player.Jo(b.videoId,void 0,void 0,!0,!0,b),c&&c.XI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.$V.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.$V.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Wt()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Xrb(this);this.D&&Wrb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new w6(this.player),g.N(this,this.endScreen),g.xU(this.player,this.endScreen.element,4))};g.ZV("endscreen",Yrb);})(_yt_player);
