(function(g){var window=this;'use strict';var Vsb=function(a,b){g.V.call(this,{I:"button",La:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.Ta("click",this.onClick,this);this.updateValue("title",g.pU(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.nU(b.Te(),this.element))},Wsb=function(a){g.V.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.lh);this.T(a,"onStateChange",this.R2)},Xsb=function(a){g.$V.call(this,a);
this.B=new g.RK(this);this.j=new Wsb(this.player);this.j.hide();g.xU(this.player,this.j.element,4);a.xg()&&(this.load(),g.bv(a.getRootNode(),"ytp-player-minimized",!0))};
g.w(Vsb,g.V);Vsb.prototype.onClick=function(){this.J.ob("onExpandMiniplayer")};g.w(Wsb,g.V);g.k=Wsb.prototype;
g.k.show=function(){this.j=new g.Ou(this.P2,null,this);this.j.start();if(!this.G){this.tooltip=new g.nY(this.player,this);g.N(this,this.tooltip);g.xU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Yd=new g.DW(this.player);g.N(this,this.Yd);this.B=new g.V({I:"div",S:"ytp-miniplayer-scrim"});g.N(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.hT);var a=new g.V({I:"button",La:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.qG()]});g.N(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.gT);a=new Vsb(this.player,this);g.N(this,a);a.Ja(this.B.element);this.C=new g.V({I:"div",S:"ytp-miniplayer-controls"});g.N(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.hT);var b=new g.V({I:"div",S:"ytp-miniplayer-button-container"});g.N(this,b);b.Ja(this.C.element);a=new g.V({I:"div",S:"ytp-miniplayer-play-button-container"});g.N(this,a);a.Ja(this.C.element);var c=new g.V({I:"div",S:"ytp-miniplayer-button-container"});
g.N(this,c);c.Ja(this.C.element);this.N=new g.BX(this.player,this,!1);g.N(this,this.N);this.N.Ja(b.element);b=new g.AX(this.player,this);g.N(this,b);b.Ja(a.element);this.nextButton=new g.BX(this.player,this,!0);g.N(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.gY(this.player,this);g.N(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.GX(this.player,this);g.N(this,this.progressBar);g.xU(this.player,this.progressBar.element,4);this.D=new g.V({I:"div",S:"ytp-miniplayer-buttons"});
g.N(this,this.D);g.xU(this.player,this.D.element,4);a=new g.V({I:"button",La:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.qG()]});g.N(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.gT);a=new g.V({I:"button",La:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Fwa()]});g.N(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.caa);this.T(this.player,"presentingplayerstatechange",this.Q2);this.T(this.player,"appresize",this.Yb);
this.T(this.player,"fullscreentoggled",this.Yb);this.Yb();this.G=!0}0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.hide.call(this);this.player.xg()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.xa.call(this)};
g.k.gT=function(){this.player.stopVideo();this.player.ob("onCloseMiniplayer")};
g.k.caa=function(){this.player.playVideo()};
g.k.hT=function(a){if(a.target===this.B.element||a.target===this.C.element)g.LL(this.player.Xb())?this.player.pauseVideo():this.player.playVideo()};
g.k.lh=function(){g.bv(this.player.getRootNode(),"ytp-player-minimized",this.player.xg())};
g.k.hg=function(){this.progressBar.Rc();this.K.Rc()};
g.k.P2=function(){this.hg();this.j&&this.j.start()};
g.k.Q2=function(a){g.SG(a.state,32)&&this.tooltip.hide()};
g.k.Yb=function(){g.L0a(this.progressBar,0,this.player.qb().getPlayerSize().width,!1);g.HX(this.progressBar)};
g.k.R2=function(a){this.player.xg()&&(0===a?this.hide():this.show())};
g.k.Te=function(){return this.tooltip};
g.k.Pt=function(a,b,c,d,e){var f=0,h=d=0,l=g.ws(a);if(b){c=g.Xu(b,"ytp-prev-button")||g.Xu(b,"ytp-next-button");var m=g.Xu(b,"ytp-play-button"),n=g.Xu(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.us(b,this.element),h=b.x,f=b.y-12):n&&(h=g.Xu(b,"ytp-miniplayer-button-top-left"),f=g.us(b,this.element),b=g.ws(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.qb().getPlayerSize().width;e=f+(e||0);l=g.He(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.w(Xsb,g.$V);g.k=Xsb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.bv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.$V.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.wl=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.ZV("miniplayer",Xsb);})(_yt_player);
